create table attack_match_6 (
id int not null auto_increment,
player char(50),
try smallint,
assist smallint,
breaks smallint,
metres smallint,
offloads smallint,
carries smallint,
primary key (id)
);

insert into attack_match_6
(player)
select 
player from players; -- inserting players from table players

update attack_match_6
set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0; -- set all 0 before inserting values

update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 33, offloads = 2, carries = 13 where player = 'Oli Kebble';
update attack_match_6 set try = 2, assist = 0, breaks = 0, metres = 49, offloads = 2, carries = 25 where player = 'Fraser Brown'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Murphy Walker'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 7 where player = 'Sintu Manjezi'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Alex Samuel'; 
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 17, offloads = 0, carries = 3 where player = 'Ryan Wilson'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 1, carries = 10 where player = 'Gregor Brown'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 14, offloads = 0, carries = 2 where player = 'Sione Vailanu'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Jamie Dobie'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Domingo Miotti'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 14, offloads = 0, carries = 5 where player = 'Rufus Mclean'; 
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 93, offloads = 0, carries = 24 where player = 'Stafford Mcdowall'; 
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 60, offloads = 3, carries = 14 where player = 'Kyle Steyn'; 
update attack_match_6 set try = 1, assist = 0, breaks = 5, metres = 181, offloads = 3, carries = 26 where player = 'Sebastian Cancelliere'; 
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 58, offloads = 0, carries = 10 where player = 'Josh Mckay'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 3 where player = 'Johnny Matthews'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Nathan Mcbeth';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 2 where player = 'Simon Berghan';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 16, offloads = 1, carries = 6 where player = 'Jp Du preez'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 7 where player = 'Lewis Bean'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Euan Ferrie'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Sean Kennedy'; 
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 121, offloads = 5, carries = 36 where player = 'Tom Jordan'; 

update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries =  0 where player = 'Nahuel Tetaz Chaparro';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries =  4 where player = 'Federico Zani';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries =  3 where player = 'Tiziano Pasquali';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 50, offloads = 1, carries =  21 where player = 'Scott Scrafton';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries =  5 where player = 'Carl Wegner';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 1, carries =  6 where player = 'Giovani Pettinelli';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries =  0 where player = 'Seb Negri';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 11, offloads = 2, carries =  15 where player = 'Henry Tyme-Stowers';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 15, offloads = 0, carries =  10 where player = 'Dewaldt Duvenage';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 49, offloads = 1, carries =  13 where player = 'Giacomo Da Re';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 103, offloads = 5, carries =  17 where player = 'Mattia Bellini';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 68, offloads = 7, carries =  25 where player = 'Marco Zanon';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 59, offloads = 3, carries =  20 where player = 'Joaquin Riera';
update attack_match_6 set try = 2, assist = 0, breaks = 5, metres = 237, offloads = 1, carries =  36 where player = 'Ignacio Mendy';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 127, offloads = 4, carries =  21 where player = 'Rhyno Smith';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Manuel Arroyo';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 0, carries =  6 where player = 'Thomas Gallo';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries =  1 where player = 'Filippo Alongi';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 1, carries =  3 where player = 'Marco Lazzaroni';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 1, carries =  5 where player = 'Braam Steyn';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 1, carries =  4 where player = 'Alessandro Izekor';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries =  0 where player = 'Alessandro Garbisi';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 0, carries =  2 where player = 'Marcus Watson';

update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 19, offloads = 0, carries =  26 where player = 'Steff Thomas';
update attack_match_6 set try = 2, assist = 0, breaks = 0, metres = 10, offloads = 1, carries =  10 where player = 'Dafydd Hughes';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries =  16 where player = 'Harri O''connor';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 1, carries =  5 where player = 'Jac Price';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries =  6 where player = 'Tom Price';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries =  0 where player = 'Aaron Shingler';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries =  0 where player = 'Dan Thomas';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 321, offloads = 5, carries =  100 where player = 'Sione Kalamafoni';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 81, offloads = 3, carries =  14 where player = 'Gareth Davies';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 0, carries =  4 where player = 'Dan Jones';
update attack_match_6 set try = 2, assist = 0, breaks = 6, metres = 220, offloads = 0, carries =  26 where player = 'Ryan Conbeer';
update attack_match_6 set try = 2, assist = 0, breaks = 1, metres = 129, offloads = 0, carries =  50 where player = 'Jonathan Davies';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 96, offloads = 2, carries =  22 where player = 'Steff Evans';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 66, offloads = 0, carries =  11 where player = 'Tom Rogers';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 171, offloads = 4, carries =  37 where player = 'Johnny Mcnicholl';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries =  6 where player = 'Shaun Evans';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries =  0 where player = 'Kemsley Mathias';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries =  2 where player = 'Willgriff Jones';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 0, carries =  10 where player = 'Morgan Jones';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries =  0 where player = 'Iwan Shenton';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries =  0 where player = 'Archie Hughes';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 29, offloads = 1, carries =  8 where player = 'Rhys Patchell';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 110, offloads = 1, carries =  17 where player = 'Corey Baldwin';

update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 25, offloads = 2, carries = 14 where player = 'Ed Byrne';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 9, offloads = 1, carries = 2 where player = 'John Mckee';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Thomas Clarkson';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 31, offloads = 2, carries = 38 where player = 'Ross Molony';
update attack_match_6 set try = 2, assist = 0, breaks = 1, metres = 54, offloads = 1, carries = 31 where player = 'Jason Jenkins';
update attack_match_6 set try = 2, assist = 0, breaks = 0, metres = 9, offloads = 0, carries = 7 where player = 'Rhys Ruddock';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 49, offloads = 1, carries = 15 where player = 'Scott Penny';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 35, offloads = 0, carries = 15 where player = 'Max Deegan';
update attack_match_6 set try = 3, assist = 0, breaks = 1, metres = 157, offloads = 1, carries = 26 where player = 'Luke Mcgrath';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 22, offloads = 2, carries = 13 where player = 'Ross Byrne';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 39 , offloads = 0, carries = 12 where player = 'Dave Kearney';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 116, offloads = 4, carries = 29 where player = 'Charlie Ngatai';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 60, offloads = 1, carries = 8 where player = 'Liam Turner';
update attack_match_6 set try = 2, assist = 0, breaks = 7, metres = 224, offloads = 4, carries = 33 where player = 'Rob Russell';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Chris Cosgrave';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Tadgh Mcelroy';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 14, offloads = 0, carries = 5 where player = 'Michael Milne';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Vakh Abdaladze';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 2 where player = 'Brian Deeny';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 1, carries = 13 where player = 'Martin Moloney';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Nick Mccarthy';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Charlie Tector';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Ben Brownlee';

update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 31, offloads = 2, carries = 10 where player = 'Jean-Pierre Smith';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 32, offloads = 2, carries = 25 where player = 'PJ Botha';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 0, carries = 15 where player = 'Ruan Dreyer';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 4 where player = 'Willem Alberts';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 0, carries = 18 where player = 'Reinhard Nothnagel';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 74, offloads = 2, carries = 27 where player = 'Emmanuel Tshituka';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 73, offloads = 2, carries = 34 where player = 'Ruan Venter';
update attack_match_6 set try = 5, assist = 0, breaks = 4, metres = 209, offloads = 1, carries = 44 where player = 'Francke Horn';
update attack_match_6 set try = 1, assist = 0, breaks = 3, metres = 91, offloads = 2, carries = 8 where player = 'Sanele Nohamba';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 51, offloads = 2, carries = 12 where player = 'Jordan Hendrikse';
update attack_match_6 set try = 2, assist = 0, breaks = 4, metres = 115, offloads = 1, carries = 18 where player = 'Quan Horn';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 119, offloads = 3, carries = 37 where player = 'Marius Louw';
update attack_match_6 set try = 1, assist = 0, breaks = 5, metres = 147, offloads = 1, carries = 27 where player = 'Henco Van wyk';
update attack_match_6 set try = 2, assist = 0, breaks = 1, metres = 85, offloads = 1, carries = 85 where player = 'Edwill Van der merwe';
update attack_match_6 set try = 2, assist = 0, breaks = 3, metres = 264, offloads = 6, carries = 37 where player = 'Andries Coetzee';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 8 where player = 'Jaco Visagie';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Morgan Naude';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 37, offloads = 3, carries = 21 where player = 'Ruan Smith';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 1, carries = 18 where player = 'Pieter Jansen van vuren';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 45, offloads = 1, carries = 16 where player = 'Sibusiso Sangweni';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 40, offloads = 3, carries = 9 where player = 'Morné Van den berg';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 19, offloads = 1, carries = 3 where player = 'Gianni Lombard';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 36, offloads = 1, carries = 10 where player = 'Zander Du plessis';

update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 3 where player = 'Brok Harris';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 14, offloads = 0, carries = 10 where player = 'Joseph Dweba';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 7 where player = 'Neethling Fouché';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 1, carries = 3 where player = 'Ernst Van rhyn';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 7, offloads = 0, carries = 18 where player = 'Marvin Orie';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 33, offloads = 0, carries = 8 where player = 'Junior Pokomela';
update attack_match_6 set try = 1, assist = 0, breaks = 4, metres = 163, offloads = 5, carries = 27 where player = 'Hacjivah Dayimani';
update attack_match_6 set try = 1, assist = 0, breaks = 3, metres = 132, offloads = 3, carries = 29 where player = 'Evan Roos';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 60, offloads = 1, carries = 12 where player = 'Paul De wet';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 57, offloads = 7, carries = 27 where player = 'Manie Libbok';
update attack_match_6 set try = 1, assist = 0, breaks = 3, metres = 91, offloads = 0, carries = 7 where player = 'Leolin Zas';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 64, offloads = 1, carries = 16 where player = 'Sacha Mngomezulu';
update attack_match_6 set try = 0, assist = 0, breaks = 3, metres = 183, offloads = 5, carries = 35 where player = 'Dan Du plessis';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 94, offloads = 1, carries = 15 where player = 'Angelo Davids';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 110, offloads = 3, carries = 45 where player = 'Clayton Blommetjies';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 7, offloads = 1, carries = 3 where player = 'JJ Kotzé';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 6 where player = 'Ali Vermaak';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Sazi Sandi';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 2 where player = 'Ben-Jason Dixon';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 6 where player = 'Willie Engelbrecht';
update attack_match_6 set try = 2, assist = 0, breaks = 0, metres = 7, offloads = 3, carries = 9 where player = 'Nama Xaba';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 11, offloads = 0, carries = 2 where player = 'Herschel Jantjies';
update attack_match_6 set try = 2, assist = 0, breaks = 3, metres = 128, offloads = 1, carries = 15 where player = 'Suleiman Hartzenberg';

update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 35, offloads = 2, carries = 22 where player = 'Aki Seiuli';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 21, offloads = 0, carries = 22 where player = 'Elliot Dee';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 1, carries = 28 where player = 'Lloyd Fairbrother';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Joe Davies';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 52, offloads = 1, carries = 17 where player = 'Sean Lonsdale';
update attack_match_6 set try = 1, assist = 0, breaks = 3, metres = 89, offloads = 0, carries = 27 where player = 'Aaron Wainwright';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 24, offloads = 1, carries = 8 where player = 'Harri Keddie';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 110, offloads = 1, carries = 49 where player = 'Ross Moriarty';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 70, offloads = 2, carries = 25 where player = 'Rhodri Williams';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 34, offloads = 0, carries = 11 where player = 'Sam Davies';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 138, offloads = 2, carries = 23 where player = 'Jared Rosser';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 46, offloads = 2, carries = 10 where player = 'Max Clark';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 62, offloads = 1, carries = 15 where player = 'Steff Hughes';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'David Richards';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 275, offloads = 4, carries = 51 where player = 'Angus O''brien';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'James Benjamin';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 1, carries = 6 where player = 'Rob Evans';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 0, carries = 9 where player = 'Chris Coleman';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Huw Taylor';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 2, carries = 12 where player = 'Ben Fry';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 11, offloads = 1, carries = 5 where player = 'Gonzalo Bertranou';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 80, offloads = 1, carries = 18 where player = 'JJ Hanrahan';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Aneurin Owen';

update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 1, carries = 12 where player = 'Juan Manuel Pittinari';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 8 where player = 'Jacques Du toit';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 1, carries = 12 where player = 'Matteo Nocera';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 21, offloads = 3, carries = 19 where player = 'Leonard Krumov';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 1, carries = 7 where player = 'Andrea Zambonin';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 55, offloads = 2, carries = 23 where player = 'Davide Ruggeri';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 1, carries = 24 where player = 'Iacopo Bianchi';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 109, offloads = 1, carries = 29 where player = 'Taina Fox-matamua';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 8, offloads = 2, carries = 7 where player = 'Chris Cook';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 30, offloads = 3, carries = 13 where player = 'Tiff Eden';
update attack_match_6 set try = 2, assist = 0, breaks = 2, metres = 173, offloads = 1, carries = 22 where player = 'Jacopo Trulla';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 38, offloads = 2, carries = 15 where player = 'Damiano Mazza';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 78, offloads = 3, carries = 18 where player = 'Tommaso Boni';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 61, offloads = 1, carries = 9 where player = 'Latu Latunipulu';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 117, offloads = 1, carries = 19 where player = 'Richard Kriel';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 33, offloads = 0, carries = 11 where player = 'Marco Manfredi';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 3 where player = 'Alessio Sanavia';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 46, offloads = 1, carries = 16 where player = 'Muhamed Hasa';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Jan Uys';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Giacomo Ferrari';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Ratko Jelic';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 68, offloads = 4, carries = 26 where player = 'Geronimo Prisciantelli';
update attack_match_6 set try = 2, assist = 0, breaks = 4, metres = 165, offloads = 3, carries = 22 where player = 'Lorenzo Pani';

update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 47, offloads = 1, carries = 30 where player = 'Dave Kilcoyne';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 60, offloads = 2, carries = 15 where player = 'Diarmuid Barron';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'John Ryan';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 0, carries = 10 where player = 'Edwin Edogbo';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Eoin O''connor';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 89, offloads = 2, carries = 31 where player = 'Jack O''donoghue';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 50, offloads = 1, carries = 13 where player = 'John Hodnett';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 0, carries = 3 where player = 'Alex Kendellen';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 52, offloads = 3, carries = 12 where player = 'Paddy Patterson';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 88, offloads = 4, carries = 24 where player = 'Jack Crowley';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 66, offloads = 0, carries = 15 where player = 'Patrick Campbell';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 2, carries = 12 where player = 'Rory Scannell';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 153, offloads = 4, carries = 41 where player = 'Malakai Fekitoa';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 74, offloads = 3, carries = 22 where player = 'Shane Daly';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 75, offloads = 4, carries = 22 where player = 'Mike Haley';
update attack_match_6 set try = 2, assist = 0, breaks = 0, metres = 23, offloads = 0, carries = 26 where player = 'Nial Scannell';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 2 where player = 'Josh Wycherley';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 0, carries = 9 where player = 'Roman Salanoa';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Evan O''connell';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Cian Hurley';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Neil Cronin';
update attack_match_6 set try = 1, assist = 0, breaks = 3, metres = 63, offloads = 4, carries = 28 where player = 'Ben Healy';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 75, offloads = 0, carries = 8 where player = 'Simon Zebo';

update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 0, carries = 18 where player = 'Andrew Warwick';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 43, offloads = 0, carries = 14 where player = 'Tom Stewart';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 15 where player = 'Marty Moore';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 21, offloads = 1, carries = 24 where player = 'Alan O''connor';
update attack_match_6 set try = 2, assist = 0, breaks = 0, metres = 28, offloads = 0, carries = 32 where player = 'Sam Carter';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 16, offloads = 0, carries = 7 where player = 'David Mccann';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Sean Reffell';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 40, offloads = 1, carries = 6 where player = 'Duane Vermeulen';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 3 where player = 'Nathan Doak';
update attack_match_6 set try = 2, assist = 0, breaks = 1, metres = 25, offloads = 2, carries = 19 where player = 'Billy Burns';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 63, offloads = 0, carries = 3 where player = 'Ethan Mcilroy';
update attack_match_6 set try = 3, assist = 0, breaks = 6, metres = 160, offloads = 3, carries = 41 where player = 'Luke Marshall';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'James Hume';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Ben Moxham';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 104, offloads = 1, carries = 20 where player = 'Stewart Moore';
update attack_match_6 set try = 2, assist = 0, breaks = 0, metres = 51, offloads = 0, carries = 24 where player = 'John Andrew';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Rory Sutherland';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Gareth Milasinovich';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 22, offloads = 0, carries = 12 where player = 'Cormac Izuchukwu';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 1, carries = 13 where player = 'Jordi Murphy';
update attack_match_6 set try = 2, assist = 0, breaks = 5, metres = 50, offloads = 1, carries = 11 where player = 'John Cooney';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 2 where player = 'Angus Curtis';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 105, offloads = 1, carries = 8 where player = 'Crai Gilroy';

update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 0, carries = 5 where player = 'Rhys Henry';
update attack_match_6 set try = 2, assist = 0, breaks = 19, metres = 1, offloads = 0, carries = 23 where player = 'Scott Baldwin';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 8 where player = 'Tom Botha';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 1, offloads = 21, carries = 8 where player = 'Rhys Davies';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 3 where player = 'Huw Sutton';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 0, carries = 9 where player = 'Ethan Roots';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 0, carries = 5 where player = 'Harri Deaves';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 105, offloads = 3, carries = 42 where player = 'Morgan Morris';
update attack_match_6 set try = 1, assist = 0, breaks = 4, metres = 44, offloads = 0, carries = 9 where player = 'Reuben Morgan-williams';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 118, offloads = 4, carries = 30 where player = 'Jack Walsh';
update attack_match_6 set try = 4, assist = 0, breaks = 7, metres = 172, offloads = 3, carries = 25 where player = 'Keelan Giles';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Keiran Williams';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Tiaan Thomas-wheeler';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 90, offloads = 2, carries = 14 where player = 'Luke Morgan';
update attack_match_6 set try = 0, assist = 0, breaks = 3, metres = 186, offloads = 4, carries = 48 where player = 'Max Nagy';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Sam Parry';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 3 where player = 'Garyn Phillips';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Ben Warren';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 3 where player = 'Jack Regan';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Tristan Davies';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Matthew Aubrey';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Luke Scully';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 1, carries = 6 where player = 'Cai Evans';

update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 10 where player = 'Denis Bucley';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 32, offloads = 1, carries = 14 where player = 'Dylan Tierney-martin';
update attack_match_6 set try = 3, assist = 0, breaks = 0, metres = 45, offloads = 3, carries = 23 where player = 'Jack Aungier';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 0, carries = 16 where player = 'Oisin Downling';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 0, carries = 8 where player = 'Gavin Thornbury';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 0, carries = 16 where player = 'Shamus Hurley-langton';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 80, offloads = 1, carries = 33 where player = 'Conor Oliver';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 21, offloads = 1, carries = 17 where player = 'Jarrad Butler';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 52, offloads = 0, carries = 15 where player = 'Caolin Blade';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 18, offloads = 2, carries = 9 where player = 'Jack Carty';
update attack_match_6 set try = 0, assist = 0, breaks = 6, metres = 292, offloads = 3, carries = 45 where player = 'John Porch';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 106, offloads = 1, carries = 24 where player = 'David Hawkshaw';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 69, offloads = 4, carries = 26 where player = 'Tom Farrell';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 52, offloads = 0, carries = 3 where player = 'Alex Wootton';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 44, offloads = 0, carries = 8 where player = 'Tiernan O''halloran';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 0, carries = 3 where player = 'Grant Stewart';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 2 where player = 'Jordan Duggan';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 1 where player = 'Sam Illo';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Darragh Murray';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 51, offloads = 2, carries = 32 where player = 'Paul Boyle';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 64, offloads = 1, carries = 15 where player = 'Kieran Marmion';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 0, carries = 10 where player = 'Tom Daly';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Adam Byrne';

update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 26, offloads = 1, carries = 18 where player = 'Gerhard Steenekamp';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 12, offloads = 0, carries = 15 where player = 'Bismarck Du plessis';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 0, carries = 11 where player = 'François Klopper';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 26, offloads = 0, carries = 14 where player = 'Walt Steenkamp';
update attack_match_6 set try = 1, assist = 0, breaks = 3, metres = 88, offloads = 4, carries = 44 where player = 'Ruan Nortje';
update attack_match_6 set try = 3, assist = 0, breaks = 0, metres = 116, offloads = 3, carries = 59 where player = 'Marcell Coetzee';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 75, offloads = 3, carries = 43 where player = 'Marco Van staden';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 17, offloads = 0, carries = 13 where player = 'WJ Steenkamp';
update attack_match_6 set try = 2, assist = 0, breaks = 2, metres = 97, offloads = 2, carries = 10 where player = 'Zak Burger';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 109, offloads = 2, carries = 19 where player = 'Chris Smith';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 102, offloads = 0, carries = 11 where player = 'Sbu Nkosi';
update attack_match_6 set try = 0, assist = 0, breaks = 3, metres = 61, offloads = 1, carries = 13 where player = 'Harold Vorster';
update attack_match_6 set try = 2, assist = 0, breaks = 3, metres = 103, offloads = 1, carries = 18 where player = 'Cornal Hendricks';
update attack_match_6 set try = 1, assist = 0, breaks = 6, metres = 321, offloads = 5, carries = 36 where player = 'David Kriel';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 42, offloads = 1, carries = 11 where player = 'Johan Goosen';
update attack_match_6 set try = 2, assist = 0, breaks = 1, metres = 26, offloads = 2, carries = 19 where player = 'Jan-Hendrik Wessels';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 1, carries = 17 where player = 'Simphiwe Matanzima';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 1, carries = 16 where player = 'Mornay Smith';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 4, offloads = 0, carries = 7 where player = 'Janko Swanepoel';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 27, offloads = 1, carries = 8 where player = 'Ruan Vermaak';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 88, offloads = 2, carries = 19 where player = 'Embrose Papier';
update attack_match_6 set try = 2, assist = 0, breaks = 2, metres = 50, offloads = 0, carries = 5 where player = 'Stravino Jacobs';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 89, offloads = 3, carries = 16 where player = 'Wandisile Simelane';

update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 25, offloads = 1, carries = 11 where player = 'Ntuthuko Mchunu';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 45, offloads = 0, carries = 18 where player = 'Kerron Van vuuren';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 27, offloads = 0, carries = 16 where player = 'Thomas Du toit';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 2 where player = 'Gerbrandt Grobler';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 5 where player = 'Hyron Andrews';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 74, offloads = 1, carries = 37 where player = 'Dylan Richardson';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 1, carries = 5 where player = 'Vincent Tshituka';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 162, offloads = 2, carries = 35 where player = 'Phepsi Buthelezi';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 2 where player = 'Cameron Wright';
update attack_match_6 set try = 0, assist = 0, breaks = 3, metres = 110, offloads = 1, carries = 15 where player = 'Boeta Chamberlain';
update attack_match_6 set try = 3, assist = 0, breaks = 5, metres = 166, offloads = 0, carries = 16 where player = 'Thaakir Abrahams';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 68, offloads = 2, carries = 20  where player = 'Ben Tapuai';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Francois Venter';
update attack_match_6 set try = 3, assist = 0, breaks = 6, metres = 157, offloads = 1, carries = 14 where player = 'Werner Kok';
update attack_match_6 set try = 3, assist = 0, breaks = 5, metres = 186, offloads = 4, carries = 27 where player = 'Aphelele Fassi';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 4 where player = 'Dan Jooste';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 3 where player = 'Dian Bleluer';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 0, carries = 4 where player = 'Carlu Sadie';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 2 where player = 'Justin Basson';
update attack_match_6 set try = 0, assist = 0, breaks = 3, metres = 68, offloads = 0, carries = 16 where player = 'James Venter';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 41, offloads = 2, carries = 12 where player = 'Sikhumbuzo Notshe';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 111, offloads = 1, carries = 13 where player = 'Grant Williams';
update attack_match_6 set try = 0, assist = 0, breaks = 2, metres = 74, offloads = 0, carries = 11 where player = 'Marnus Potgieter';

update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 51, offloads = 2, carries = 21 where player = 'Rhys Carre';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 0, carries = 5 where player = 'Kirby Mihill';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 1, carries = 9 where player = 'Dimitri Arhip';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 20, offloads = 2, carries = 37 where player = 'Josh Turnbull';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 5 where player = 'Rory Thornton';
update attack_match_6 set try = 2, assist = 0, breaks = 2, metres = 73, offloads = 1, carries = 31 where player = 'James Botham';
update attack_match_6 set try = 1, assist = 0, breaks = 3, metres = 155, offloads = 1, carries = 28 where player = 'Thomas Young';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 26, offloads = 0, carries = 14 where player = 'James Ratti';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 0, carries = 2 where player = 'Lloyd Williams';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 106, offloads = 0, carries = 18 where player = 'Jarrod Evans';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 98, offloads = 0, carries = 13 where player = 'Theo Cabango';
update attack_match_6 set try = 0, assist = 1, breaks = 6, metres = 179, offloads = 3, carries = 32 where player = 'Max Llewellyn';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 41, offloads = 0, carries = 9 where player = 'Mason Grady';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 75, offloads = 0, carries = 15 where player = 'Jason Harries';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 24, offloads = 0, carries = 8 where player = 'Ben Thomas';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 35, offloads = 0, carries = 13 where player = 'Liam Belcher';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 5 where player = 'Corey Domachowski';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Will Davies-King';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Teddy Williams';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Gwilym Bradley';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Ellis Bevan';
update attack_match_6 set try = 1, assist = 0, breaks = 5, metres = 167, offloads = 3, carries = 26 where player = 'Aled Summerhill';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Cam Winnet';

update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 43, offloads = 0, carries = 23 where player = 'Boan Venter';
update attack_match_6 set try = 2, assist = 0, breaks = 2, metres = 53, offloads = 1, carries = 6 where player = 'Adam Mcburney';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 11, offloads = 1, carries = 10 where player = 'Luan De bruin';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Pierce Phillips';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 6, offloads = 0, carries = 4 where player = 'Jamie Hodgson';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 52, offloads = 2, carries = 18 where player = 'Ben Muncaster';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 69, offloads = 1, carries = 33 where player = 'Luke Crosbie';
update attack_match_6 set try = 1, assist = 0, breaks = 0, metres = 167, offloads = 4, carries = 68 where player = 'Viliame Mata';
update attack_match_6 set try = 0, assist = 0, breaks = 1, metres = 10, offloads = 0, carries = 4 where player = 'Charlie Shiel';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 41, offloads = 4, carries = 10 where player = 'Charlie Savala';
update attack_match_6 set try = 1, assist = 0, breaks = 1, metres = 29, offloads = 1, carries = 4 where player = 'Wes Goosen';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 120, offloads = 2, carries = 28 where player = 'Chris Dean';
update attack_match_6 set try = 1, assist = 0, breaks = 2, metres = 38, offloads = 0, carries = 8 where player = 'Matt Currie';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Jack Blain';
update attack_match_6 set try = 1, assist = 0, breaks = 3, metres = 93, offloads = 0, carries = 20 where player = 'Emiliano Boffelli';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 0, carries = 2 where player = 'Harrison Courtney';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Nick Auterac';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 4 where player = 'Angus Williams';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 6 where player = 'Marshall Sykes';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Connor Boyle';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 1, carries = 7 where player = 'Henry Pyrgos';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 11, offloads = 0, carries = 4 where player = 'Jaco Van der walt';
update attack_match_6 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Cameron Scott';
