create table attack_match_8 (
id int not null auto_increment,
player char(50),
try smallint,
assist smallint,
breaks smallint,
metres smallint,
offloads smallint,
carries smallint,
team char(50),
primary key (id)
);

insert into attack_match_8
(player, try, assist, breaks, metres, offloads, carries, team)
select
player, try, assist, breaks, metres, offloads, carries, team from attack_match_7;

update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 3 where player = 'Brok Harris';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 39, offloads = 1, carries = 23 where player = 'Joseph Dweba';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 12, offloads = 0, carries = 16 where player = 'Neethling Fouché';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 17, offloads = 2, carries = 13 where player = 'Ernst Van rhyn';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 7, offloads = 0, carries = 18 where player = 'Marvin Orie';
update attack_match_8 set try = 2, assist = 0, breaks = 0, metres = 36, offloads = 1, carries = 13 where player = 'Junior Pokomela';
update attack_match_8 set try = 2, assist = 0, breaks = 5, metres = 224, offloads = 7, carries = 43 where player = 'Hacjivah Dayimani';
update attack_match_8 set try = 1, assist = 0, breaks = 4, metres = 164, offloads = 6, carries = 42 where player = 'Evan Roos';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 80, offloads = 4, carries = 21 where player = 'Paul De wet';
update attack_match_8 set try = 0, assist = 0, breaks = 3, metres = 74, offloads = 7, carries = 30 where player = 'Manie Libbok';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 6, offloads = 1, carries = 4 where player = 'Deon Fourie';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 10 where player = 'Steven Kitshoff';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 3 where player = 'Frans Malherbe';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 1, carries = 10 where player = 'Salmaan Moerat';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 6 where player = 'Andre Smith';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 23, offloads = 2, carries = 10 where player = 'Marcel Theunissen';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 45, offloads = 1, carries = 18 where player = 'André-Hugo Venter';
update attack_match_8 set try = 2, assist = 0, breaks = 6, metres = 198, offloads = 1, carries = 18 where player = 'Leolin Zas';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 81, offloads = 1, carries = 24 where player = 'Sacha Mngomezulu';
update attack_match_8 set try = 1, assist = 0, breaks = 5, metres = 257, offloads = 8, carries = 49 where player = 'Dan Du plessis';
update attack_match_8 set try = 1, assist = 0, breaks = 4, metres = 188, offloads = 1, carries = 21 where player = 'Angelo Davids';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 349, offloads = 10, carries = 65 where player = 'Clayton Blommetjies';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 11, offloads = 2, carries = 5 where player = 'JJ Kotzé';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 1, carries = 7 where player = 'Ali Vermaak';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 3 where player = 'Sazi Sandi';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 22, offloads = 0, carries = 6 where player = 'Ben-Jason Dixon';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 12, offloads = 0, carries = 6 where player = 'Willie Engelbrecht';
update attack_match_8 set try = 3, assist = 0, breaks = 0, metres = 14, offloads = 3, carries = 12 where player = 'Nama Xaba';
update attack_match_8 set try = 2, assist = 0, breaks = 1, metres = 14, offloads = 0, carries = 3 where player = 'Herschel Jantjies';
update attack_match_8 set try = 2, assist = 0, breaks = 4, metres = 162, offloads = 1, carries = 18 where player = 'Suleiman Hartzenberg';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 81, offloads = 1, carries = 24 where player = 'Sacha Feinberg-mngomezulu';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 21, offloads = 0, carries = 10 where player = 'Alapati Leiua';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Godlen Masimla';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 19, offloads = 1, carries = 6 where player = 'Seabelo Senatia';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 49, offloads = 3, carries = 15 where player = 'Damian Willemse';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 14, offloads = 0, carries = 7 where player = 'Gary Porter';
update attack_match_8  set try = 0, assist = 0, breaks = 2, metres = 59, offloads = 3, carries = 12 where player = 'Cornel Smit';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 12, offloads = 4, carries = 6 where player = 'Kade Wolhuter';

update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 22, offloads = 0, carries = 31 where player = 'Steff Thomas';
update attack_match_8 set try = 2, assist = 0, breaks = 0, metres = 24, offloads = 2, carries = 20 where player = 'Dafydd Hughes';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 0, carries = 25 where player = 'Harri O''connor';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 1, carries = 11 where player = 'Jac Price';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 8 where player = 'Tom Price';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 21, offloads = 4, carries = 16 where player = 'Aaron Shingler';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 41, offloads = 2, carries = 9 where player = 'Dan Thomas';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 375, offloads = 5, carries = 127 where player = 'Sione Kalamafoni';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 0, carries = 9 where player = 'Shaun Evans';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 7, offloads = 1, carries = 7 where player = 'Kemsley Mathias';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 7, offloads = 1, carries = 10 where player = 'Willgriff Jones';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 0, carries = 12 where player = 'Morgan Jones';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 0, carries = 9 where player = 'Shaun Evans';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 1, carries = 4 where player = 'Kemsley Mathias';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 8 where player = 'Willgriff Jones';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 0, carries = 12 where player = 'Morgan Jones';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 4 where player = 'Iwan Shenton';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 29, offloads = 1, carries = 9 where player = 'Archie Hughes';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 34, offloads = 3, carries = 14 where player = 'Rhys Patchell';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 110, offloads = 1, carries = 17 where player = 'Corey Baldwin';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 12, offloads = 1, carries = 5 where player = 'Taylor Davies';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 0, carries = 4 where player = 'Dan Davis';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 31, offloads = 0, carries = 23 where player = 'Ryan Elias';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 84, offloads = 4, carries = 24 where player = 'Vaea Fifita';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Luca Giannini';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Josh Helps';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Alex Jeffries';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 0, carries = 17 where player = 'Wyn Jones';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 0, carries = 12 where player = 'Morgan Jones';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Samson Lee';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 2 where player = 'Tomas Lezana';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 121, offloads = 7, carries = 46 where player = 'Sam Lousi';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 30, offloads = 1, carries = 35 where player = 'Josh Macleod';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 1, carries = 4 where player = 'Kemsley Mathias';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Sam O''connor';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 27, offloads = 0, carries = 28 where player = 'Ken Owens';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Phil Price';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Lewis Rawlins';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Iestyn Rees';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 20 where player = 'Javan Sebastian';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 4 where player = 'Iwan Shenton';
update attack_match_8 set try = 0, assist = 0, breaks = 3, metres = 87, offloads = 6, carries = 37 where player = 'Blade Thomson';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Carwin Tuipulotou';
update attack_match_8 set try = 0, assist = 0, breaks = 3, metres = 122, offloads = 4, carries = 22 where player = 'Gareth Davies';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 24, offloads = 1, carries = 14 where player = 'Dan Jones';
update attack_match_8 set try = 4, assist = 0, breaks = 12, metres = 400, offloads = 1, carries = 44 where player = 'Ryan Conbeer';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 190, offloads = 4, carries = 69 where player = 'Jonathan Davies';
update attack_match_8 set try = 2, assist = 0, breaks = 3, metres = 127, offloads = 4, carries = 32 where player = 'Steff Evans';
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 176, offloads = 1, carries = 28 where player = 'Tom Rogers';
update attack_match_8 set try = 1, assist = 0, breaks = 5, metres = 343, offloads = 9, carries = 58 where player = 'Johnny Mcnicholl';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 110, offloads = 1, carries = 17 where player = 'Corey Baldwin';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 29, offloads = 1, carries = 6 where player = 'Dane Blacker';
update attack_match_8 set try = 3, assist = 0, breaks = 6, metres = 179, offloads = 0, carries = 39 where player = 'Sam Costelow';
update attack_match_8 set try = 0, assist = 0, breaks = 5, metres = 160, offloads = 8, carries = 26 where player = 'Gareth Davies';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 139, offloads = 0, carries = 35 where player = 'Leigh Halfpenny';
update attack_match_8 set try = 0, assist = 0, breaks = 3, metres = 100, offloads = 3, carries = 19 where player = 'Kieran Hardy';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Archie Hughes';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Eddie James';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 30, offloads = 0, carries = 5 where player = 'Ioan Nicholas';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Joe Roberts';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 25, offloads = 0, carries = 16 where player = 'Scott Williams';
update attack_match_8 set try = 2, assist = 0, breaks = 4, metres = 144, offloads = 2, carries = 32 where player = 'Johnny Williams';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Harri Williams';

update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 0, carries = 23 where player = 'Andrew Warwick';
update attack_match_8 set try = 4, assist = 0, breaks = 1, metres = 114, offloads = 1, carries = 37 where player = 'Tom Stewart';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 8, offloads = 1, carries = 24 where player = 'Marty Moore';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 28, offloads = 1, carries = 35 where player = 'Alan O''connor';
update attack_match_8 set try = 2, assist = 0, breaks = 0, metres = 32, offloads = 0, carries = 43 where player = 'Sam Carter';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 23, offloads = 0, carries = 18 where player = 'David Mccann';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 23, offloads = 1, carries = 23 where player = 'Jordi Murphy';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 61, offloads = 2, carries = 15 where player = 'Duane Vermeulen';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 6, offloads = 1, carries = 5 where player = 'Frank Bradshaw';
update attack_match_8 set try = 2, assist = 0, breaks = 0, metres= 29, offloads = 0, carries = 37 where player = 'Sam Carter';
update attack_match_8 set try= 1, assist = 0, breaks = 0, metres= 20, offloads = 1, carries = 11 where player = 'Rob Herring';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 0, offloads = 0, carries = 3 where player = 'Greg Jones';
update attack_match_8 set try= 0, assist = 0, breaks = 1, metres= 9, offloads = 1, carries = 3 where player = 'Declan Moore';
update attack_match_8 set try= 1, assist = 0, breaks = 0, metres= 28, offloads = 1, carries = 35 where player = 'Alan O''connor';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 27, offloads = 0, carries = 21 where player = 'Eric O''sullivan';
update attack_match_8 set try= 1, assist = 0, breaks = 1, metres= 42, offloads = 0, carries = 27 where player = 'Tom O''toole';
update attack_match_8 set try= 2, assist = 0, breaks = 0, metres= 68, offloads = 2, carries = 38 where player = 'Marcus Rea';
update attack_match_8 set try= 2, assist = 0, breaks = 0, metres= 15, offloads = 1, carries = 24 where player = 'Callum Reid';
update attack_match_8 set try= 2, assist = 0, breaks = 1, metres= 100, offloads = 0, carries = 26 where player = 'Tom Stewart';
update attack_match_8 set try= 0, assist = 0, breaks = 1, metres= 124, offloads = 0, carries = 41 where player = 'Nick Timoney';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 15, offloads = 1, carries = 11 where player = 'Jeffery Toomaga-allen';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 14, offloads = 1, carries = 17 where player = 'Kieran Treadwell';
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 28, offloads = 1, carries = 12 where player = 'Nathan Doak';
update attack_match_8 set try = 2, assist = 0, breaks = 1, metres = 25, offloads = 2, carries = 19 where player = 'Billy Burns';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 123, offloads = 1, carries = 17 where player = 'Ethan Mcilroy';
update attack_match_8 set try = 3, assist = 0, breaks = 6, metres = 210, offloads = 3, carries = 56 where player = 'Luke Marshall';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 38, offloads = 2, carries = 18 where player = 'James Hume';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 21, offloads = 0, carries = 2 where player = 'Ben Moxham';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 167, offloads = 1, carries = 29 where player = 'Stewart Moore';
update attack_match_8 set try = 3, assist = 0, breaks = 0, metres = 58, offloads = 1, carries = 28 where player = 'John Andrew';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 4 where player = 'Rory Sutherland';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Gareth Milasinovich';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 37, offloads = 1, carries = 24 where player = 'Cormac Izuchukwu';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 80, offloads = 2, carries = 41 where player = 'Matty Rea';
update attack_match_8 set try = 2, assist = 0, breaks = 5, metres = 50, offloads = 1, carries = 12 where player = 'John Cooney';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 7 where player = 'Angus Curtis';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 105, offloads = 1, carries = 8 where player = 'Crai Gilroy';
update attack_match_8 set try= 1, assist = 0, breaks = 3, metres= 124, offloads = 2, carries = 10 where player = 'Robert Baloucoune';
update attack_match_8 set try= 0, assist = 0, breaks = 4, metres= 336, offloads = 5, carries = 56 where player = 'Mike Lowry';
update attack_match_8 set try= 1, assist = 0, breaks = 1, metres= 85, offloads = 6, carries = 13 where player = 'Rob Lyttle';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 5, offloads = 0, carries = 5 where player = 'Ian Madigan';
update attack_match_8 set try= 2, assist = 0, breaks = 1, metres= 147, offloads = 8, carries = 50 where player = 'Stuart Mccloskey';
update attack_match_8 set try= 2, assist = 0, breaks = 4, metres= 204, offloads = 3, carries = 33 where player = 'Stewart Moore';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 21, offloads = 0, carries = 2 where player = 'Ben Moxham';
update attack_match_8 set try= 0, assist = 0, breaks = 2, metres= 121, offloads = 0, carries = 15 where player = 'Aaron Sexton';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 0, offloads = 0, carries = 1 where player = 'Dave Shanahan';
update attack_match_8 set try= 0, assist = 0, breaks = 3, metres= 223, offloads = 5, carries = 39 where player = 'Jacob Stockdale';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 8, offloads = 0, carries = 3 where player = 'Jake Flannery';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 2, offloads = 1, carries = 4 where player = 'Iain Henderson';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 2, offloads = 0, carries = 1 where player = 'Micheal Mcdonald';

update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 12, offloads = 1, carries = 17 where player = 'Juan Manuel Pittinari';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 0, carries = 17 where player = 'Jacques Du toit';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 1, carries = 22 where player = 'Matteo Nocera';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 30, offloads = 5, carries = 26 where player = 'Leonard Krumov';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 12, offloads = 1, carries = 13 where player = 'Andrea Zambonin';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 65, offloads = 2, carries = 30 where player = 'Davide Ruggeri';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 27, offloads = 1, carries = 39 where player = 'Iacopo Bianchi';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 127, offloads = 2, carries = 35 where player = 'Taina Fox-matamua';
update attack_match_8 set try = 0, assist = 0, breaks = 3, metres = 43, offloads = 1, carries = 18 where player = 'Luca Bigi';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 5, offloads = 1, carries = 7 where player = 'Josh Furno';
update attack_match_8 set try= 1, assist = 0, breaks = 2, metres= 41, offloads = 0, carries = 18 where player = 'Ion Neculai';
update attack_match_8 set try= 2, assist = 0, breaks = 3, metres= 75, offloads = 2, carries = 21 where player = 'MJ Pelser';
update attack_match_8 set try= 0, assist = 0, breaks = 1, metres= 11, offloads = 0, carries = 11 where player = 'Giampietro Ribaldi';
update attack_match_8 set try= 1, assist = 0, breaks = 0, metres= 14, offloads = 0, carries = 12 where player = 'Luca Rizzoli';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 40, offloads = 2, carries = 28 where player = 'Dave Sisi';
update attack_match_8 set try= 1, assist = 0, breaks = 1, metres= 54, offloads = 2, carries = 23 where player = 'Gabriele Venditti';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 14, offloads = 0, carries = 10 where player = 'Guido Volpi';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 31, offloads = 5, carries = 16 where player = 'Chris Cook';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 48, offloads = 4, carries = 18 where player = 'Tiff Eden';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 203, offloads = 2, carries = 31 where player = 'Jacopo Trulla';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 78, offloads = 3, carries = 19 where player = 'Damiano Mazza';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 78, offloads = 3, carries = 19 where player = 'Tommaso Boni';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 107, offloads = 1, carries = 16 where player = 'Latu Latunipulu';
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 175, offloads = 4, carries = 31 where player = 'Richard Kriel';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 35, offloads = 0, carries = 17 where player = 'Marco Manfredi';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 2, carries = 6 where player = 'Alessio Sanavia';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 54, offloads = 1, carries = 19 where player = 'Muhamed Hasa';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 6 where player = 'Jan Uys';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 0, carries = 7 where player = 'Giacomo Ferrari';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 1, carries = 3 where player = 'Ratko Jelic';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 115, offloads = 8, carries = 44 where player = 'Geronimo Prisciantelli';
update attack_match_8 set try = 3, assist = 0, breaks = 5, metres = 239, offloads = 5, carries = 35 where player = 'Lorenzo Pani';
update attack_match_8 set try= 1, assist = 0, breaks = 6, metres= 281, offloads = 12, carries = 42 where player = 'Pierre Bruno';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 3, offloads = 1, carries = 3 where player = 'Nicolò Casilio';
update attack_match_8 set try= 1, assist = 0, breaks = 1, metres= 48, offloads = 2, carries = 10 where player = 'Erich Cronje';
update attack_match_8 set try= 1, assist = 0, breaks = 2, metres= 66, offloads = 3, carries = 22 where player = 'Alessandro Fusco';
update attack_match_8 set try= 2, assist = 0, breaks = 7, metres= 142, offloads = 5, carries = 32 where player = 'Simone Gesi';
update attack_match_8 set try= 0, assist = 0, breaks = 2, metres= 73, offloads = 3, carries = 30 where player = 'Enrico Lucchin';
update attack_match_8 set try= 1, assist = 0, breaks = 1, metres= 33, offloads = 0, carries = 7 where player = 'Franco (jr) smith';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 0, offloads = 0, carries = 1 where player = 'Nicolò Teneggi';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 0, offloads = 0, carries = 1 where player = 'Riccardo Genovese';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 12, offloads = 2, carries = 10 where player = 'Matt Kvesic';

update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 32, offloads = 2, carries = 27 where player = 'Gerhard Steenekamp';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 29, offloads = 0, carries = 23 where player = 'Bismarck Du plessis';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 11, offloads = 0, carries = 18 where player = 'François Klopper';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 27, offloads = 0, carries = 15 where player = 'Walt Steenkamp';
update attack_match_8 set try = 2, assist = 0, breaks = 4, metres = 115, offloads = 4, carries = 56 where player = 'Ruan Nortje';
update attack_match_8 set try = 4, assist = 0, breaks = 1, metres = 141, offloads = 3, carries = 65 where player = 'Marcell Coetzee';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 82, offloads = 3, carries = 49 where player = 'Marco Van staden';
update attack_match_8 set try = 2, assist = 0, breaks = 1, metres = 71, offloads = 0, carries = 30 where player = 'WJ Steenkamp';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 21, offloads = 1, carries = 16 where player = 'Johan Grobbelaar';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 0, carries = 13 where player = 'Fracois Klopper';
update attack_match_8 set try = 3, assist = 0, breaks = 1, metres = 212, offloads = 3, carries = 76 where player = 'Elrigh Louw';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 7, offloads = 0, carries = 3 where player = 'Reinhardt Ludwig';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 11, offloads = 0, carries = 3 where player = 'Mihlali Mosi';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 3 where player = 'Dylan Smith';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 27, offloads = 0, carries = 15 where player = 'Walt Steenkamp';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 46, offloads = 0, carries = 22 where player = 'WJ Steenkamp';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 5 where player = 'Jacques Van rooyen';
update attack_match_8 set try = 3, assist = 0, breaks = 3, metres = 140, offloads = 3, carries = 17 where player = 'Zak Burger';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 133, offloads = 5, carries = 31 where player = 'Chris Smith';
update attack_match_8 set try = 0, assist = 0, breaks = 5, metres = 129, offloads = 3, carries = 29 where player = 'Harold Vorster';
update attack_match_8 set try = 2, assist = 0, breaks = 6, metres = 148, offloads = 4, carries = 25 where player = 'Cornal Hendricks';
update attack_match_8 set try = 3, assist = 0, breaks = 12, metres = 525, offloads = 7, carries = 54 where player = 'David Kriel';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 102, offloads = 2, carries = 19 where player = 'Johan Goosen';
update attack_match_8 set try = 3, assist = 0, breaks = 1, metres = 50, offloads = 5, carries = 27 where player = 'Jan-Hendrik Wessels';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 1, carries = 20 where player = 'Simphiwe Matanzima';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 1, carries = 17 where player = 'Mornay Smith';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 15, offloads = 3, carries = 19 where player = 'Janko Swanepoel';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 27, offloads = 1, carries = 8 where player = 'Ruan Vermaak';
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 122, offloads = 3, carries = 22 where player = 'Embrose Papier';
update attack_match_8 set try = 3, assist = 0, breaks = 5, metres = 149, offloads = 1, carries = 13 where player = 'Stravino Jacobs';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 239, offloads = 3, carries = 25 where player = 'Wandisile Simelane';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 263, offloads = 5, carries = 33 where player = 'Kurt-Lee Arendse';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 42, offloads = 0, carries = 13 where player = 'Stedman Gans';
update attack_match_8 set try = 0, assist = 0, breaks = 3, metres = 92, offloads = 5, carries = 25 where player = 'Lionel Mapoe';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 21, offloads = 0, carries = 2 where player = 'Canan Moodie';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 132, offloads = 0, carries = 14 where player = 'Sbu Nkosi';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 4 where player = 'Morne Steyn';
update attack_match_8 set try = 0, assist = 0, breaks = 4, metres = 80, offloads = 1, carries = 20 where player = 'Harold Vorster';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 8, offloads = 0, carries = 5 where player = 'Nizaam Carr';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 0, carries = 1 where player = 'Cyle Brink';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 13, offloads = 1, carries = 2 where player = 'Marco Jansen van vuren';

update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 17, offloads = 0, carries = 17 where player = 'Rhys Henry';
update attack_match_8 set try = 2, assist = 0, breaks = 0, metres = 35, offloads = 2, carries = 34 where player = 'Scott Baldwin';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 10 where player = 'Tom Botha';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 28, offloads = 1, carries = 29 where player = 'Rhys Davies';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 20, offloads = 0, carries = 14 where player = 'Huw Sutton';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 77, offloads = 0, carries = 29 where player = 'Ethan Roots';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 20, offloads = 0, carries = 12 where player = 'Harri Deaves';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 220, offloads = 4, carries = 72 where player = 'Morgan Morris';
update attack_match_8 set try = 2, assist = 0, breaks = 5, metres = 53, offloads = 3, carries = 12 where player = 'Reuben Morgan-williams';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 146, offloads = 5, carries = 38 where player = 'Jack Walsh';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 4, offloads = 1, carries = 20 where player = 'Adam Beard';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 0, offloads = 0, carries = 1 where player = 'Tristan Davies';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 1, offloads = 2, carries = 5 where player = 'Tomas Francis';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 25, offloads = 0, carries = 11 where player = 'Will Griffiths';
update attack_match_8 set try= 1, assist = 0, breaks = 0, metres= 25, offloads = 0, carries = 38 where player = 'Dewi Lake';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 7, offloads = 0, carries = 13 where player = 'Dan Lydiate';
update attack_match_8 set try= 1, assist = 0, breaks = 2, metres= 124, offloads = 2, carries = 43 where player = 'Jac Morgan';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 2, offloads = 0, carries = 4 where player = 'Jack Regan';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 37, offloads = 0, carries = 30 where player = 'Nicky Smith';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 0, offloads = 0, carries = 1 where player = 'Gareth Thomas';
update attack_match_8 set try= 0, assist = 0, breaks = 2, metres= 14, offloads = 2, carries = 14 where player = 'Justin Tipuric';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 5, offloads = 0, carries = 4 where player = 'Ben Warren';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 11, offloads = 2, carries = 22 where player = 'Alun Wyn jones';
update attack_match_8 set try = 4, assist = 0, breaks = 9, metres = 230, offloads = 4, carries = 32 where player = 'Keelan Giles';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 82, offloads = 1, carries = 20 where player = 'Keiran Williams';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 22, offloads = 2, carries = 12 where player = 'Tiaan Thomas-wheeler';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 120, offloads = 3, carries = 21 where player = 'Luke Morgan';
update attack_match_8 set try = 0, assist = 0, breaks = 3, metres = 301, offloads = 6, carries = 70 where player = 'Max Nagy';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 21, offloads = 0, carries = 7 where player = 'Sam Parry';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 7 where player = 'Garyn Phillips';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 3 where player = 'Ben Warren';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 8 where player = 'Jack Regan';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Matthew Aubrey';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Luke Scully';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 14, offloads = 1, carries = 7 where player = 'Cai Evans';
update attack_match_8 set try= 1, assist = 0, breaks = 1, metres= 61, offloads = 1, carries = 10 where player = 'Gareth Anscombe';
update attack_match_8 set try= 0, assist = 0, breaks = 2, metres= 107, offloads = 6, carries = 45 where player = 'Mike Collins';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 8, offloads = 1, carries = 6 where player = 'Cai Evans';
update attack_match_8 set try= 0, assist = 0, breaks = 1, metres= 106, offloads = 2, carries = 22 where player = 'Joe Hawkins';
update attack_match_8 set try= 2, assist = 0, breaks = 5, metres= 60, offloads = 3, carries = 13 where player = 'Reuben Morgan-williams';
update attack_match_8 set try= 0, assist = 0, breaks = 3, metres= 233, offloads = 5, carries = 59 where player = 'Max Nagy';
update attack_match_8 set try= 2, assist = 0, breaks = 3, metres= 186, offloads = 4, carries = 31 where player = 'George North';
update attack_match_8 set try= 1, assist = 0, breaks = 3, metres= 181, offloads = 6, carries = 45 where player = 'Jack Walsh';
update attack_match_8 set try= 1, assist = 0, breaks = 1, metres= 88, offloads = 4, carries = 33 where player = 'Owen Walkin';
update attack_match_8 set try= 1, assist = 0, breaks = 1, metres= 41, offloads = 3, carries = 22 where player = 'Rhys Webb';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 1, offloads = 0, carries = 1 where player = 'Bradley Davies';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 2, offloads = 0, carries = 5 where player = 'Will Hickey';

update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 4 where player = 'Nahuel Tetaz Chaparro';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 7 where player = 'Federico Zani';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 3 where player = 'Tiziano Pasquali';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 5 where player = 'Manuel Arroyo';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 0, carries = 11 where player = 'Thomas Gallo';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries =  2 where player = 'Filippo Alongi';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 50, offloads = 1, carries = 22 where player = 'Scott Scrafton';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 7, offloads = 0, carries =  8 where player = 'Carl Wegner';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 1, carries = 12 where player = 'Giovani Pettinelli';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 32, offloads = 1, carries = 23 where player = 'Seb Negri';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 23, offloads = 2, carries =  25 where player = 'Henry Tyme-Stowers';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 1, carries =  3 where player = 'Marco Lazzaroni';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 9, offloads = 1, carries =  7 where player = 'Braam Steyn';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 1, carries =  5 where player = 'Alessandro Izekor';
update attack_match_8 set try = 2, assist = 0, breaks = 1, metres = 178, offloads = 1, carries = 57 where player = 'Lorenzo Cannone';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 24, offloads = 2, carries = 19 where player = 'Niccolo Cannone';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Matteo Drudi';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Corniel Els';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Riccardo Favretto';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 9 where player = 'Simone Ferrari';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 64, offloads = 2, carries = 33 where player = 'Toa Halafihi';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 47, offloads = 0, carries = 32 where player = 'Michele Lamaro';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 32, offloads = 1, carries = 33 where player = 'Gianmarco Lucchesi';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 34, offloads = 1, carries = 23 where player = 'Ivan Nemer';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 20, offloads = 0, carries = 22 where player = 'Giacomo Nicotera';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Nicola Piantella';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 60, offloads = 3, carries = 33 where player = 'Federico Ruzza';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Cherif Traore';
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 91, offloads = 2, carries = 27 where player = 'Manuel Zuliani';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 16, offloads = 0, carries = 16 where player = 'Dewaldt Duvenage';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 66, offloads = 1, carries =  19 where player = 'Giacomo Da Re';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 105, offloads = 5, carries =  18 where player = 'Mattia Bellini';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 92, offloads = 7, carries = 33 where player = 'Marco Zanon';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 59, offloads = 3, carries =  20 where player = 'Joaquin Riera';
update attack_match_8 set try = 2, assist = 0, breaks = 5, metres = 243, offloads = 1, carries =  42 where player = 'Ignacio Mendy';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 213, offloads = 4, carries = 29 where player = 'Rhyno Smith';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries =  0 where player = 'Alessandro Garbisi';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 31, offloads = 1, carries = 7 where player = 'Marcus Watson';
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 224, offloads = 2, carries = 43 where player = 'Tomas Albornoz';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 28, offloads = 0, carries = 7 where player = 'Giuliano Avaca';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 61, offloads = 3, carries = 32 where player = 'Nacho Brex';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Joey Caputo';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 31, offloads = 0, carries = 6 where player = 'Filippo Drago';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 37, offloads = 0, carries = 6 where player = 'Manfredi Albanese';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 27, offloads = 2, carries = 9 where player = 'Sam Hidalgo-Clyne';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Leonardo Marin';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 108, offloads = 2, carries = 25 where player = 'Tommaso Menoncello';
update attack_match_8 set try = 3, assist = 0, breaks = 7, metres = 86, offloads = 2, carries = 20 where player = 'Edoardo Padovani';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Dewi Passarella';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 1, carries = 4 where player = 'Onisi Ratave';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 11, offloads = 2, carries = 4 where player = 'Iliesa Tavuyara';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 11, offloads = 2, carries = 4 where player = 'Matteo Minozzi';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 18, offloads = 0, carries = 2 where player = 'Jacob Umaga';

update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 72, offloads = 0, carries = 44 where player = 'Boan Venter';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 58, offloads = 1, carries = 8 where player = 'Adam Mcburney';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 14, offloads = 1, carries = 15 where player = 'Luan De bruin';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Pierce Phillips';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 11, offloads = 0, carries = 13 where player = 'Jamie Hodgson';
update attack_match_8 set try = 2, assist = 0, breaks = 1, metres = 107, offloads = 3, carries = 43 where player = 'Ben Muncaster';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 105, offloads = 1, carries = 49 where player = 'Luke Crosbie';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 216, offloads = 5, carries = 87 where player = 'Viliame Mata';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 35, offloads = 0, carries = 11 where player = 'Harrison Courtney';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Nick Auterac';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 12 where player = 'Angus Williams';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 0, carries = 20 where player = 'Marshall Sykes';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Connor Boyle';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 3 where player = 'Lee Roy atalifo';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 21, offloads = 0, carries = 13 where player = 'Dave Cherry';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 3, carries = 20 where player = 'Grant Gilchrist';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 60, offloads = 3, carries = 41 where player = 'Nick Haining';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Mesulame Kunavula';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 56, offloads = 1, carries = 16 where player = 'Stuart Mcinally';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 31, offloads = 0, carries = 16 where player = 'Wp Nel';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 32, offloads = 0, carries = 28 where player = 'Jamie Ritchie';
update attack_match_8 set try = 2, assist = 0, breaks = 1, metres = 35, offloads = 0, carries = 39 where player = 'Pierre Schoeman';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 12, offloads = 2, carries = 26 where player = 'Sam Skinner';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 31, offloads = 6, carries = 22 where player = 'Hamish Watson';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 14, offloads = 0, carries = 17 where player = 'Glen Young';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 12, offloads = 0, carries = 6 where player = 'Charlie Shiel';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 64, offloads = 6, carries = 18 where player = 'Charlie Savala';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 101, offloads = 1, carries = 15 where player = 'Wes Goosen';
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 168, offloads = 4, carries = 42 where player = 'Chris Dean';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 44, offloads = 0, carries = 14 where player = 'Matt Currie';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 1 where player = 'Jack Blain';
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 119, offloads = 0, carries = 22 where player = 'Emiliano Boffelli';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 21, offloads = 1, carries = 10 where player = 'Henry Pyrgos';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 11, offloads = 0, carries = 4 where player = 'Jaco Van der walt';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Cameron Scott';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 147, offloads = 6, carries = 30 where player = 'Mark Bennett';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 1, carries = 1 where player = 'Jack Blain';
update attack_match_8 set try = 8, assist = 0, breaks = 12, metres = 442, offloads = 1, carries = 40 where player = 'Darcy Graham';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 82, offloads = 1, carries = 25 where player = 'Damien Hoyland';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Cammy Hutchinson';
update attack_match_8 set try = 3, assist = 0, breaks = 2, metres = 257, offloads = 3, carries = 56 where player = 'Henry Immelman';
update attack_match_8 set try = 1, assist = 0, breaks = 4, metres = 126, offloads = 2, carries = 20 where player = 'Blair Kinghorn';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 158, offloads = 3, carries = 45 where player = 'James Lang';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Freddie Owsley';
update attack_match_8 set try = 2, assist = 0, breaks = 3, metres = 81, offloads = 3, carries = 10 where player = 'Duhan Van der merwe';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 38, offloads = 2, carries = 8 where player = 'Ben Vellacot';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 88, offloads = 4, carries = 57 where player = 'Nick Haining';

update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 42, offloads = 3, carries = 22 where player = 'Ed Byrne';
update attack_match_8 set try = 2, assist = 0, breaks = 0, metres = 29, offloads = 1, carries = 11 where player = 'John Mckee';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 10, offloads = 0, carries = 7 where player = 'Thomas Clarkson';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 1 where player = 'Tadgh Mcelroy';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 27, offloads = 0, carries = 13 where player = 'Michael Milne';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 0, carries = 5 where player = 'Vakh Abdaladze';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 14, offloads = 0, carries = 24 where player = 'Michael Alaalatoa';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 42, offloads = 1, carries = 25 where player = 'Ryan Baird';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 6 where player = 'Tadhg Furlong';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 7, offloads = 0, carries = 12 where player = 'Cian Healy';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 44, offloads = 2, carries = 19 where player = 'Ronan Kelleher';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 31, offloads = 0, carries = 25 where player = 'Andrew Porter';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'James Tracy';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 35, offloads = 3, carries = 45 where player = 'Ross Molony';
update attack_match_8 set try = 2, assist = 0, breaks = 1, metres = 82, offloads = 1, carries = 39 where player = 'Jason Jenkins';
update attack_match_8 set try = 2, assist = 0, breaks = 0, metres = 32, offloads = 0, carries = 23 where player = 'Rhys Ruddock';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 82, offloads = 2, carries = 26 where player = 'Scott Penny';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 149, offloads = 0, carries = 42 where player = 'Max Deegan';
update attack_match_8 set try = 3, assist = 0, breaks = 2, metres = 189, offloads = 2, carries = 38 where player = 'Luke Mcgrath';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 90, offloads = 4, carries = 22 where player = 'Ross Byrne';
update attack_match_8 set try = 2, assist = 0, breaks = 1, metres = 103, offloads = 0, carries = 21 where player = 'Dave Kearney';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 131, offloads = 5, carries = 35 where player = 'Charlie Ngatai';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 116, offloads = 2, carries = 15 where player = 'Liam Turner';
update attack_match_8 set try = 6, assist = 0, breaks = 8, metres = 280, offloads = 4, carries = 43 where player = 'Rob Russell';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 85, offloads = 0, carries = 10 where player = 'Chris Cosgrave';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 3 where player = 'Brian Deeny';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 1, carries = 14 where player = 'Martin Moloney';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 3 where player = 'Nick Mccarthy';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Charlie Tector';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 12, offloads = 0, carries = 1 where player = 'Ben Brownlee';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 34, offloads = 0, carries = 23 where player = 'Jack Conan';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 19, offloads = 0, carries = 18 where player = 'Will Connors';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 68, offloads = 2, carries = 27 where player = 'Caelan Doris';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 35, offloads = 0, carries = 13 where player = 'Joe Mccarthy';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 0, carries = 8 where player = 'Michael Milne';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Charlie Ryan';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 18, offloads = 0, carries = 20 where player = 'James Ryan';
update attack_match_8 set try = 6, assist = 0, breaks = 3, metres = 123, offloads = 0, carries = 48 where player = 'Dan Sheehan';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Alex Soroka';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'James Tracy';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 91, offloads = 4, carries = 18 where player = 'Josh Van der flier';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 83, offloads = 4, carries = 19 where player = 'Ross Byrne';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 16, offloads = 0, carries = 5 where player = 'Harry Byrne';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 99, offloads = 1, carries = 12 where player = 'Chris Cosgrave';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 81, offloads = 2, carries = 12 where player = 'Cormac Foley';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 57, offloads = 2, carries = 12 where player = 'Ciaran Frawley';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Jamison Gibson-park';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 115, offloads = 3, carries = 45 where player = 'Robbie Henshaw';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 119, offloads = 2, carries = 20 where player = 'Jamie Osborne';

update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 75, offloads = 3, carries = 27 where player = 'Oli Kebble';
update attack_match_8 set try = 3, assist = 0, breaks = 0, metres = 69, offloads = 3, carries = 41 where player = 'Fraser Brown'; 
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 21, offloads = 0, carries = 10 where player = 'Murphy Walker'; 
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 7 where player = 'Johnny Matthews'; 
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 42, offloads = 0, carries = 23 where player = 'George Turner';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 2 where player = 'Nathan Mcbeth';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 5 where player = 'Simon Berghan';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 0, carries = 24 where player = 'Jamie Bhatti';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Allan Dell';
update attack_match_8 set try = 2, assist = 0, breaks = 0, metres = 36, offloads = 1, carries = 37 where player = 'Zander Fagerson';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Enrique Pieretto Heiland';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 6 where player = 'Murphy Walker';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 28, offloads = 1, carries = 24 where player = 'Sintu Manjezi'; 
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 29, offloads = 1, carries = 16 where player = 'Alex Samuel'; 
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 21, offloads = 1, carries = 11 where player = 'Jp Du preez'; 
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 10 where player = 'Lewis Bean';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 8, offloads = 3, carries = 17 where player = 'Scott Cummings';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 24, offloads = 0, carries = 30 where player = 'Richie Gray';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 41, offloads = 0, carries = 4 where player = 'Euan Ferrie';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 17, offloads = 1, carries = 3 where player = 'Ryan Wilson'; 
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 35, offloads = 2, carries = 22 where player = 'Gregor Brown'; 
update attack_match_8 set try = 2, assist = 0, breaks = 1, metres = 118, offloads = 4, carries = 25 where player = 'Sione Vailanu';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 41, offloads = 0, carries = 4 where player = 'Euan Ferrie'; 
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 1 where player = 'Rory Darge';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 122, offloads = 7, carries = 41 where player = 'Jack Dempsey';
update attack_match_8 set try = 2, assist = 0, breaks = 0, metres = 40, offloads = 0, carries = 26 where player = 'Matt Fagerson';
update attack_match_8 set try = 4, assist = 0, breaks = 2, metres = 116, offloads = 0, carries = 26 where player = 'Tom Gordon';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Ally Miller';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 17, offloads = 1, carries = 5 where player = 'Jamie Dobie'; 
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 19, offloads = 1, carries = 6 where player = 'Domingo Miotti'; 
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 67, offloads = 0, carries = 18 where player = 'Rufus Mclean'; 
update attack_match_8 set try = 2, assist = 0, breaks = 3, metres = 176, offloads = 4, carries = 49 where player = 'Stafford Mcdowall'; 
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 123, offloads = 3, carries = 27 where player = 'Kyle Steyn'; 
update attack_match_8 set try = 3, assist = 0, breaks = 9, metres = 367, offloads = 10, carries = 54 where player = 'Sebastian Cancelliere'; 
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 262, offloads = 10, carries = 36 where player = 'Josh Mckay'; 
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 31, offloads = 2, carries = 3 where player = 'Sean Kennedy'; 
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 170, offloads = 6, carries = 43 where player = 'Tom Jordan'; 
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Walter Fifita';
update attack_match_8 set try = 1, assist = 0, breaks = 4, metres = 207, offloads = 4, carries = 34 where player = 'Cole Forbes';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Joel Hodgson';
update attack_match_8 set try = 2, assist = 0, breaks = 5, metres = 167, offloads = 4, carries = 31 where player = 'George Horne';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 87, offloads = 1, carries = 22 where player = 'Sam Johnson';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Huw Jones';
update attack_match_8 set try = 2, assist = 0, breaks = 3, metres = 137, offloads = 1, carries = 34 where player = 'Stafford Mcdowall';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 50, offloads = 3, carries = 15 where player = 'Ali Price';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 39, offloads = 0, carries = 6 where player = 'Ollie Smith';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 76, offloads = 3, carries = 18 where player = 'Kyle Steyn';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 2 where player = 'Ross Thompson';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Duncan Weir';

update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 53, offloads = 1, carries = 37 where player = 'Dave Kilcoyne';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 98, offloads = 3, carries = 26 where player = 'Diarmuid Barron';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 6, offloads = 0, carries = 7 where player = 'John Ryan';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 0, carries = 14 where player = 'Edwin Edogbo';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 6 where player = 'Eoin O''connor';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 125, offloads = 4, carries = 41 where player = 'Jack O''donoghue';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 112, offloads = 3, carries = 33 where player = 'John Hodnett';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 69, offloads = 1, carries = 24 where player = 'Alex Kendellen';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 63, offloads = 5, carries = 20 where player = 'Paddy Patterson';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 125, offloads = 5, carries = 40 where player = 'Jack Crowley';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 39, offloads = 0, carries = 13 where player = 'Thomas Ahern';
update attack_match_8 set try= 1, assist = 0, breaks = 0, metres= 8, offloads = 0, carries = 11 where player = 'Stephen Archer';
update attack_match_8 set try= 1, assist = 0, breaks = 1, metres= 44, offloads = 1, carries = 28 where player = 'Tadhg Beirne';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 6, offloads = 2, carries = 8 where player = 'Scott Buckley';
update attack_match_8 set try= 2, assist = 0, breaks = 0, metres= 80, offloads = 3, carries = 41 where player = 'Gavin Coombes';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 39, offloads = 3, carries = 30 where player = 'Jean Kleyn';
update attack_match_8 set try= 1, assist = 0, breaks = 0, metres= 25, offloads = 2, carries = 20 where player = 'Keynan Knox';
update attack_match_8 set try= 1, assist = 0, breaks = 0, metres= 24, offloads = 1, carries = 18 where player = 'Jeremy Loughman';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 28, offloads = 2, carries = 15 where player = 'Peter O''mahony';
update attack_match_8 set try= 1, assist = 0, breaks = 0, metres= 67, offloads = 1, carries = 24 where player = 'Jack O''sullivan';
update attack_match_8 set try= 0, assist = 0, breaks = 1, metres= 46, offloads = 0, carries = 6 where player = 'Ruadhan Quinn';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 96, offloads = 1, carries = 22 where player = 'Patrick Campbell';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 30, offloads = 3, carries = 21 where player = 'Rory Scannell';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 166, offloads = 4, carries = 47 where player = 'Malakai Fekitoa';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 155, offloads = 4, carries = 37 where player = 'Shane Daly';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 189, offloads = 4, carries = 43 where player = 'Mike Haley';
update attack_match_8 set try = 3, assist = 0, breaks = 0, metres = 31, offloads = 1, carries = 30 where player = 'Nial Scannell';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 6 where player = 'Josh Wycherley';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 10, offloads = 0, carries = 13 where player = 'Roman Salanoa';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Evan O''connell';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 2 where player = 'Cian Hurley';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 15, offloads = 0, carries = 1 where player = 'Neil Cronin';
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 66, offloads = 4, carries = 28 where player = 'Ben Healy';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 89, offloads = 0, carries = 10 where player = 'Simon Zebo';
update attack_match_8 set try= 0, assist = 0, breaks = 1, metres= 107, offloads = 2, carries = 20 where player = 'Joey Carbery';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 53, offloads = 3, carries = 24 where player = 'Craig Casey';
update attack_match_8 set try= 1, assist = 0, breaks = 3, metres= 140, offloads = 2, carries = 30 where player = 'Liam Coombes';
update attack_match_8 set try= 0, assist = 0, breaks = 1, metres= 103, offloads = 5, carries = 32 where player = 'Jack Crowley';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 3, offloads = 1, carries = 3 where player = 'Keith Earls';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 10, offloads = 0, carries = 3 where player = 'Chris Farrell';
update attack_match_8 set try= 0, assist = 0, breaks = 1, metres= 166, offloads = 4, carries = 47 where player = 'Malakai Fekitoa';
update attack_match_8 set try= 0, assist = 0, breaks = 1, metres= 60, offloads = 2, carries = 12 where player = 'Antoine Frisch';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 114, offloads = 0, carries = 36 where player = 'Dan Goggin';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 0, offloads = 0, carries = 2 where player = 'Conor Murray';
update attack_match_8 set try= 1, assist = 0, breaks = 3, metres= 126, offloads = 2, carries = 18 where player = 'Calvin Nash';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 63, offloads = 5, carries = 20 where player = 'Paddy Patterson';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 17, offloads = 1, carries = 10 where player = 'Conor Phillips';

update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 11 where player = 'Denis Bucley';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 45, offloads = 1, carries = 22 where player = 'Dylan Tierney-martin';
update attack_match_8 set try = 3, assist = 0, breaks = 0, metres = 64, offloads = 3, carries = 36 where player = 'Jack Aungier';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 20, offloads = 0, carries = 23 where player = 'Oisin Downling';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 0, carries = 13 where player = 'Gavin Thornbury';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 1, carries = 23 where player = 'Shamus Hurley-langton';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 96, offloads = 1, carries = 50 where player = 'Conor Oliver';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 40, offloads = 2, carries = 28 where player = 'Jarrad Butler';
update attack_match_8 set try= 1, assist = 0, breaks = 0, metres= 17, offloads = 2, carries = 19 where player = 'Finlay Bealham';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 3, offloads = 0, carries = 2 where player = 'Ciaran Booth';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 24, offloads = 1, carries = 22 where player = 'Jarrad Butler';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 14, offloads = 3, carries = 28 where player = 'Peter Dooley';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 11, offloads = 0, carries = 19 where player = 'Leva Fifita';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 51, offloads = 1, carries = 39 where player = 'Dave Heffernan';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 34, offloads = 0, carries = 36 where player = 'Josh Murphy';
update attack_match_8 set try= 1, assist = 0, breaks = 0, metres= 10, offloads = 1, carries = 12 where player = 'Niall Murray';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 14, offloads = 1, carries = 13 where player = 'Cian Prendergast';
update attack_match_8 set try= 1, assist = 0, breaks = 0, metres= 45, offloads = 1, carries = 22 where player = 'Dylan Tierney-martin';
update attack_match_8 set try = 2, assist = 0, breaks = 1, metres = 75, offloads = 0, carries = 26 where player = 'Caolin Blade';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 60, offloads = 3, carries = 18 where player = 'Jack Carty';
update attack_match_8 set try = 1, assist = 0, breaks = 4, metres = 159, offloads = 1, carries = 30 where player = 'David Hawkshaw';
update attack_match_8 set try = 0, assist = 0, breaks = 3, metres = 188, offloads = 4, carries = 47 where player = 'Tom Farrell';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 66, offloads = 1, carries = 14 where player = 'Tiernan O''halloran';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 14, offloads = 0, carries = 5 where player = 'Grant Stewart';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 1, offloads = 0, carries = 4 where player = 'Jordan Duggan';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 4 where player = 'Sam Illo';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Darragh Murray';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 63, offloads = 2, carries = 41 where player = 'Paul Boyle';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 66, offloads = 1, carries = 16 where player = 'Kieran Marmion';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 23, offloads = 0, carries = 13 where player = 'Tom Daly';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 0, carries = 2 where player = 'Adam Byrne';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 88, offloads = 0, carries = 20 where player = 'Conor Fitzgerald';
update attack_match_8 set try= 3, assist = 0, breaks = 5, metres= 279, offloads = 9, carries = 49 where player = 'Mack Hansen';
update attack_match_8 set try= 1, assist = 0, breaks = 4, metres= 159, offloads = 1, carries = 30 where player = 'David Hawkshaw';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 68, offloads = 0, carries = 15 where player = 'Oran Mcnulty';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 66, offloads = 1, carries = 14 where player = 'Tiernan O''halloran';
update attack_match_8 set try= 1, assist = 0, breaks = 7, metres= 362, offloads = 5, carries = 60 where player = 'John Porch';
update attack_match_8 set try= 1, assist = 0, breaks = 1, metres= 86, offloads = 0, carries = 24 where player = 'Byron Ralston';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 14, offloads = 1, carries = 7 where player = 'Colm Reilly';
update attack_match_8 set try= 1, assist = 0, breaks = 2, metres= 97, offloads = 1, carries = 13 where player = 'Alex Wooton';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 37, offloads = 0, carries = 8 where player = 'Bundee Aki';
update attack_match_8 set try= 0, assist = 0, breaks = 0, metres= 5, offloads = 1, carries = 5 where player = 'Shane Delahunt';

update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 52, offloads = 2, carries = 21 where player = 'Jean-Pierre Smith';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 47, offloads = 2, carries = 34 where player = 'PJ Botha';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 20, offloads = 1, carries = 24 where player = 'Ruan Dreyer';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 4, offloads = 1, carries = 7 where player = 'Willem Alberts';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 13, offloads = 0, carries = 22 where player = 'Reinhard Nothnagel';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 125, offloads = 5, carries = 54 where player = 'Emmanuel Tshituka';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 119, offloads = 2, carries = 46 where player = 'Ruan Venter';
update attack_match_8 set try = 5, assist = 0, breaks = 4, metres = 228, offloads = 2, carries = 49 where player = 'Francke Horn';
update attack_match_8 set try = 1, assist = 0, breaks = 4, metres = 118, offloads = 4, carries = 11 where player = 'Sanele Nohamba';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 94, offloads = 2, carries = 23 where player = 'Jordan Hendrikse';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Morne Brandon';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Jaco Kriel';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Morgan Naude';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 1 where player = 'Asenathi Ntlabakanye';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 8, offloads = 0, carries = 3 where player = 'Ruben Schoeman';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 14 where player = 'Sti Sithole';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 68, offloads = 2, carries = 23 where player = 'Ruhan Straeuli';
update attack_match_8 set try = 2, assist = 0, breaks = 4, metres = 177, offloads = 2, carries = 29 where player = 'Quan Horn';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 158, offloads = 6, carries = 49 where player = 'Marius Louw';
update attack_match_8 set try = 2, assist = 0, breaks = 7, metres = 200, offloads = 1, carries = 38 where player = 'Henco Van wyk';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 128, offloads = 1, carries = 20 where player = 'Edwill Van der merwe';
update attack_match_8 set try = 2, assist = 0, breaks = 3, metres = 313, offloads = 9, carries = 44 where player = 'Andries Coetzee';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 0, carries = 8 where player = 'Jaco Visagie';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Morgan Naude';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 39, offloads = 3, carries = 24 where player = 'Ruan Smith';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 17, offloads = 1, carries = 23 where player = 'Pieter Jansen van vuren';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 63, offloads = 1, carries = 22 where player = 'Sibusiso Sangweni';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 46, offloads = 3, carries = 11 where player = 'Morné Van den berg';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 19, offloads = 1, carries = 3 where player = 'Gianni Lombard';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 79, offloads = 1, carries = 13 where player = 'Zander Du plessis';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 63, offloads = 2, carries = 15 where player = 'Jordan Hendriske';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Rabz Maxwane';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 0 where player = 'Matt More';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 26, offloads = 0, carries = 4 where player = 'Stean Pienaar';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 21, offloads = 0, carries = 1 where player = 'Andre Warner';

update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 58, offloads = 2, carries = 32 where player = 'Aki Seiuli';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 37, offloads = 1, carries = 35 where player = 'Elliot Dee';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 1, carries = 34 where player = 'Lloyd Fairbrother';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 6, offloads = 0, carries = 3 where player = 'Joe Davies';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 69, offloads = 2, carries = 27 where player = 'Sean Lonsdale';
update attack_match_8 set try = 1, assist = 0, breaks = 4, metres = 148, offloads = 2, carries = 41 where player = 'Aaron Wainwright';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 77, offloads = 2, carries = 21 where player = 'Harri Keddie';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 240, offloads = 3, carries = 65 where player = 'Ross Moriarty';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 65, offloads = 5, carries = 29 where player = 'Taine Basham';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 28, offloads = 0, carries = 33 where player = 'Ben Carter';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 18, offloads = 0, carries = 13 where player = 'Chris Coleman';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 11, offloads = 0, carries = 10 where player = 'Rhodri Jones';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 77, offloads = 2, carries = 21 where player = 'Harry Keddie';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 16, offloads = 2, carries = 13 where player = 'George Notte';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 124, offloads = 0, carries = 38 where player = 'Bradley Roberts';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 49, offloads = 2, carries = 47 where player = 'Will Rowlands';
update attack_match_8 set try = 1, assist = 0, breaks = 4, metres = 102, offloads = 5, carries = 29 where player = 'Rhodri Williams';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 76, offloads = 5, carries = 22 where player = 'Sam Davies';
update attack_match_8 set try = 0, assist = 0, breaks = 4, metres = 165, offloads = 2, carries = 29 where player = 'Jared Rosser';
update attack_match_8 set try = 0, assist = 0, breaks = 3, metres = 54, offloads = 3, carries = 15 where player = 'Max Clark';
update attack_match_8 set try = 2, assist = 0, breaks = 4, metres = 127, offloads = 2, carries = 31 where player = 'Steff Hughes';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 75, offloads = 1, carries = 12 where player = 'David Richards';
update attack_match_8 set try = 2, assist = 0, breaks = 3, metres = 364, offloads = 5, carries = 67 where player = 'Angus O''brien';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 26, offloads = 1, carries = 8 where player = 'James Benjamin';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 1, carries = 9 where player = 'Rob Evans';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 11, offloads = 0, carries = 11 where player = 'Chris Coleman';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 1, carries = 5 where player = 'Huw Taylor';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 22, offloads = 3, carries = 21 where player = 'Ben Fry';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 19, offloads = 2, carries = 8 where player = 'Gonzalo Bertranou';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 84, offloads = 1, carries = 20 where player = 'JJ Hanrahan';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 3 where player = 'Aneurin Owen';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 117, offloads = 4, carries = 58 where player = 'Jack Dixon';
update attack_match_8 set try = 4, assist = 0, breaks = 7, metres = 415, offloads = 6, carries = 41 where player = 'Rio Dyer';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 48, offloads = 0, carries = 9 where player = 'Ashton Hewitt';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 22, offloads = 0, carries = 7 where player = 'Lewis Jones';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 14, offloads = 0, carries = 7 where player = 'Will Reed';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 155, offloads = 4, carries = 39 where player = 'Sio Tomkinson';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 75, offloads = 2, carries = 8 where player = 'Jordan Williams';
update attack_match_8 set try = 1, assist = 0, breaks = 4, metres = 102, offloads = 5, carries = 29 where player = 'Rhodri Williams';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 5, offloads = 0, carries = 1 where player = 'Ellis Shipp';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 1, carries = 3 where player = 'Matthew Schreech';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 17, offloads = 0, carries = 1 where player = 'Che Hope';

update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 41, offloads = 2, carries = 16 where player = 'Ntuthuko Mchunu';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 45, offloads = 0, carries = 18 where player = 'Kerron Van vuuren';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 28, offloads = 0, carries = 17 where player = 'Thomas Du toit';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 10, offloads = 2, carries = 11 where player = 'Gerbrandt Grobler';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 3, offloads = 1, carries = 8 where player = 'Hyron Andrews';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 75, offloads = 2, carries = 39 where player = 'Dylan Richardson';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 29, offloads = 4, carries = 11 where player = 'Vincent Tshituka';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 224, offloads = 3, carries = 44 where player = 'Phepsi Buthelezi';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 39, offloads = 1, carries = 9 where player = 'Cameron Wright';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 9 where player = 'Dian Bleuler';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 15, offloads = 2, carries = 5 where player = 'Eben Etzebeth';
update attack_match_8 set try = 1, assist = 0, breaks = 1, metres = 19, offloads = 3, carries = 10 where player = 'Reniel Hugo';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 14, offloads = 2, carries = 10 where player = 'Dan Jooste';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 26, offloads = 0, carries = 4 where player = 'Siya Kolisi';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 14, offloads = 0, carries = 3 where player = 'Bongi Mbonambi';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 41, offloads = 2, carries = 16 where player = 'Ntuthuku Mchunu';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 7, offloads = 0, carries = 2 where player = 'Ox Nche';
update attack_match_8 set try = 0, assist = 0, breaks = 4, metres = 197, offloads = 3, carries = 31 where player = 'Boeta Chamberlain';
update attack_match_8 set try = 3, assist = 0, breaks = 5, metres = 177, offloads = 0, carries = 20 where player = 'Thaakir Abrahams';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 68, offloads = 3, carries = 21 where player = 'Ben Tapuai';
update attack_match_8 set try = 0, assist = 0, breaks = 2, metres = 56, offloads = 2, carries = 17 where player = 'Francois Venter';
update attack_match_8 set try = 3, assist = 0, breaks = 6, metres = 195, offloads = 1, carries = 20 where player = 'Werner Kok';
update attack_match_8 set try = 4, assist = 0, breaks = 6, metres = 260, offloads = 5, carries = 40 where player = 'Aphelele Fassi';
update attack_match_8 set try = 1, assist = 0, breaks = 0, metres = 4, offloads = 0, carries = 4 where player = 'Dan Jooste';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 5 where player = 'Dian Bleluer';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 14, offloads = 0, carries = 13 where player = 'Carlu Sadie';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 2, offloads = 0, carries = 3 where player = 'Justin Basson';
update attack_match_8 set try = 0, assist = 0, breaks = 3, metres = 77, offloads = 1, carries = 22 where player = 'James Venter';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 88, offloads = 3, carries = 24 where player = 'Sikhumbuzo Notshe';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 111, offloads = 1, carries = 13 where player = 'Grant Williams';
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 118, offloads = 0, carries = 18 where player = 'Marnus Potgieter';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Nevaldo Fleurs';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 24, offloads = 2, carries = 9 where player = 'Jaden Hendriske';
update attack_match_8 set try = 1, assist = 0, breaks = 3, metres = 107, offloads = 5, carries = 22 where player = 'Rohan Janse Van rensburg';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 22, offloads = 0, carries = 4 where player = 'Makazole Mapimpi';
update attack_match_8 set try = 0, assist = 0, breaks = 1, metres = 68, offloads = 2, carries = 20 where player = 'Ben Tapuai';
update attack_match_8 set try = 2, assist = 0, breaks = 2, metres = 104, offloads = 0, carries = 17 where player = 'Anthony Volmink';
update attack_match_8 set try = 1, assist = 0, breaks = 2, metres = 111, offloads = 1, carries = 13 where player = 'Grant Williams';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 0, offloads = 0, carries = 1 where player = 'Fred Zeilinga';
update attack_match_8 set try = 0, assist = 0, breaks = 0, metres = 34, offloads = 0, carries = 7 where player = 'Lionel Cronje';
