create table players
(id int not null auto_increment,
player char(50),
position char(20),
age int,
height double,
weight double,
year double(4,2),
primary key (id)
);

insert into players (player, position, age, height, weight, year) values ('Cherif Traore', 'prop', 28, 1.84, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Federico Zani', 'prop', 33, 1.78, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Filippo Alongi', 'prop', 22, 1.85, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gianmarco Lucchesi', 'prop', 22, 1.84, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ivan Nemer', 'prop', 24, 1.80, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Matteo Drudi', 'prop', 22, 1.83, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nahuel Tetaz Chaparro',	'prop',	32,	1.90, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Simone Ferrari', 'prop', 28, 1.85, 124, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tiziano Pasquali', 'prop', 28, 1.85, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Corniel Els', 'hooker',	28,	1.83, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Giacomo Nicotera', 'hooker', 26, 1.83, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Thomas Gallo', 'hooker', 23, 1.76, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alessandro Izekor',	'lock',	22,	1.96, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Carl Wegner', 'Lock', 31, 2, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Federico Ruzza', 'lock', 28, 1.98, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Niccolò Cannone', 'lock', 24, 1.97, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nicola Piantella', 'lock', 21, 1.98, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Riccardo Favretto',	'lock',	20,	2, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Scott Scrafton', 'lock', 29, 2, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Seb Negri',	'lock',	28, 1.94, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Braam Steyn', 'back row', 30, 1.93,	111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Giovanni Pettinelli', 'back row', 26, 1.93, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Henry Stowers',	'back row',	27, 1.9, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lorenzo Cannone', 'back row', 21, 1.90, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Manuel Zuliani', 'back row', 22, 1.88, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marco Lazzaroni', 'back row', 27, 1.94, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Michele Lamaro', 'back row', 24, 1.88, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Toa Halafihi',	'back row',	28, 1.82, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alessandro Garbisi', 'scrum-half',	20, 1.73, 86, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dewaldt Duvenage',	'scrum-half', 34, 1.73, 82, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sam Hidalgo-Clyne', 'scrum-half', 29, 1.75, 85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Leonardo Marin', 'fly-half', 20, 1.88, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tomás Albornoz', 'fly-half', 25, 1.77, 82, 22.23);
insert into players (player, position, age, height, weight, year) values ('Filippo Drago', 'center', 20, 1.86, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ignacio Brex',	'center', 30, 1.89, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joaquin Riera', 'center', 28, 1.82, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marco Zanon', 'center', 25, 1.86, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tommaso Menoncello', 'center', 20,	1.87, 98, 22.23);
insert into players (player, position, age, height, weight, year) values ('Iliesa Tavuyara', 'winger', 32, 1.89, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marcus Watson', 'winger', 31, 1.78, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mattia Bellini', 'winger', 28, 1.93, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Onisi Ratave', 'winger', 30, 1.79, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Edoardo Padovani', 'fullback', 29, 1.91, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Giacomo Da Re', 'fullback', 23, 1.8, 83, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ignacio Mendy', 'fullback', 22, 1.87, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rhyno Smith', 'fullback', 29, 1.73, 83, 22.23);
insert into players (player, position, age, height, weight, year) values ('Brad Thyer',	'prop', 29, 1.81, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Corey Domachowsky', 'prop', 26, 1.83, 121, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dillon Lewis', 'prop', 26, 1.85, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dmitri Arhip', 'prop', 33, 1.83, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Keiron Assiratti', 'prop', 25, 1.78, 119, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rhys Carre', 'prop', 24, 1.91, 132, 22.23);
insert into players (player, position, age, height, weight, year) values ('Will Davies-King', 'prop', 24, 1.93, 128, 22.23);
insert into players (player, position, age, height, weight, year) values ('Efan Daniel', 'hooker', 19, 1.85, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kirby Myhill', 'hooker', 30,	1.83, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kristian Dacey', 'hooker', 33, 1.88, 119, 22.23);
insert into players (player, position, age, height, weight, year) values ('Liam Belcher', 'hooker', 26, 1.77, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('James Ratti', 'lock', 24, 1.96, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joe Peard', 'lock', 20, 2.01, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lopeti Timani', 'lock', 32, 1.93, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Matthew Screech', 'lock', 29, 1.96, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rory Thornton', 'lock', 27, 2.01, 119, 22.23);
insert into players (player, position, age, height, weight, year) values ('Seb Davies', 'lock', 26, 2.03, 119, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ellis Jenkins', 'back row', 29, 1.85, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('James Botham', 'back row', 24, 1.91, 104, 22.23);
insert into players (player, position, age, height, weight, year) values ('Josh Navidi', 'back row', 31, 1.85, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Josh Turnbull', 'back row', 34, 1.95, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Olly Robinson', 'back row', 31, 1.86, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Shane Lewis-hughes', 'back row', 25, 1.96, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Teddy Williams', 'back row', 21,	1.98, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Toby Faletau', 'back row', 31, 1.88, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tom Young', 'back row', 30, 1.81, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ellis Bevan', 'scrum-half', 22, 1.80, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jamie Hill', 'scrum-half', 23, 1.78, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lloyd Williams', 'scrum-half', 32, 1.83, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tomos Williams', 'scrum-half', 27, 1.80,	86, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ben Thomas', 'fly-half', 23, 1.83, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jarrod Evans', 'fly-half', 26, 1.80, 87, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rhys Priestland', 'fly-half', 35, 1.88, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Harri Millard', 'center', 26, 1.83, 94, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mason Grady', 'center', 20, 1.96, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Max Llewellyn', 'center', 23, 1.97, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rey Lee-lo', 'center', 36, 1.81, 98, 22.23);
insert into players (player, position, age, height, weight, year) values ('Willis Halaholo', 'center', 32, 1.80, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jason Harries', 'winger', 33, 1.93, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Josh Adams', 'winger', 27, 1.84, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Owen Lane', 'winger', 24, 1.85, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Aled Summerhill', 'fullback', 27, 1.88, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Liam Williams', 'fullback', 31, 1.88, 87, 22.23);
insert into players (player, position, age, height, weight, year) values ('Matthew Morgan', 'fullback', 30, 1.73, 78, 22.23);
insert into players (player, position, age, height, weight, year) values ('Denis Buckley', 'prop', 32, 1.77, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dominic Robertson-mccoy', 'prop', 28, 1.88, 122, 22.23);
insert into players (player, position, age, height, weight, year) values ('Finlay Bealham', 'prop', 31, 1.85, 123, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack Aungier', 'prop', 23, 1.88, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jordan Duggan', 'prop', 24, 1.85, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Matthew Burke', 'prop', 25, 1.79, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Peter Dooley', 'prop', 28, 1.83, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sam Illo', 'prop', 21, 1.85, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dave Heffernan', 'hooker', 31, 1.87, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dylan Tierney-martin', 'hooker', 23, 1.82, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Grant Stewart', 'hooker', 27, 1.82, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Shane Delahunt', 'hooker', 28, 1.88, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Darragh Murray', 'lock', 21, 2.01, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gavin Thornbury', 'lock', 28, 2.04, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Leva Fifita', 'lock', 33, 1.94, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Niall Murray', 'lock', 22, 2.01, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Oisin Dowling', 'lock', 25, 1.96, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cian Prendergast', 'back row', 22, 1.96, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ciaran Booth', 'back row', 22, 1.88, 104, 22.23);
insert into players (player, position, age, height, weight, year) values ('Conor Oliver', 'back row', 27, 1.83, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jarrad Butler', 'back row', 31, 1.86, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Josh Murphy', 'back row', 27, 1.98, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Oisin Mccormack', 'back row', 21, 1.83, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Paul Boyle', 'back row', 25, 1.89, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Seán Masterson', 'back row', 24, 1.90, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Shamus Hurley-langton', 'back row', 22, 1.85, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Caolin Blade', 'scrum-half', 28, 1.70, 81, 22.23);
insert into players (player, position, age, height, weight, year) values ('Colm Reilly', 'scrum-half', 23, 1.78, 78, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kieran Marmion', 'scrum-half', 30, 1.80, 85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cathal Forde', 'fly-half', 20, 1.88, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Conor Fitzgerald', 'fly-half', 25, 1.84, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack Carty', 'fly-half', 30, 1.81, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Bundee Aki', 'center', 32, 1.80, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('David Hawkshaw', 'center', 23, 1.78, 86, 22.23);
insert into players (player, position, age, height, weight, year) values ('John Porch', 'center', 28, 1.85, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Shane Jennings', 'center', 21, 1.91, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Shayne Bolton', 'center', 22, 1.88, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tom Daly', 'center', 29, 1.93, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tom Farrell', 'center', 29, 1.90, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Adam Byrne', 'winger', 28, 1.93, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alex Wootton', 'winger', 28, 1.88, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Byron Ralston', 'winger', 22, 1.84, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Diarmuid Kilgallen', 'winger', 22, 1.93, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mack Hansen', 'fullback', 24, 1.88, 89, 22.23);
insert into players (player, position, age, height, weight, year) values ('Oran Mcnulty', 'fullback', 22, 1.78, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tiernan O''halloran', 'fullback', 31, 1.88, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Aki Seiuli', 'prop', 29, 1.84, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Chris Coleman', 'prop', 24, 1.89, 130, 22.23);
insert into players (player, position, age, height, weight, year) values ('Josh Reynolds', 'prop', 23, 1.80, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Leon Brown', 'prop', 25, 1.91, 126, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lloyd Fairbrother', 'prop', 30, 1.75, 123, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rhodri Jones', 'prop', 30, 1.91, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rob Evans', 'prop', 30, 1.86, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Brad Roberts', 'hooker', 26, 1.75, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Elliot Dee', 'hooker', 28, 1.86, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ellis Shipp', 'hooker', 25, 1.79, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('James Benjamin', 'hooker', 28, 1.83, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ben Carter', 'lock', 21, 1.98, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('George Nott', 'lock', 26, 1.98, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joe Davies', 'lock', 26, 1.97, 130, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sean Lonsdale', 'lock', 25, 1.96, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Will Rowlands', 'lock', 31, 2.03, 123, 22.23);
insert into players (player, position, age, height, weight, year) values ('Aaron Wainwright', 'back row', 25, 1.90, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ben Fry', 'back row', 24, 1.86, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Harri Keddie', 'back row', 26, 1.88, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Huw Taylor', 'back row', 26, 1.96, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lennon Greggains', 'back row', 23, 1.87, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ollie Griffiths', 'back row', 27, 1.85, 104, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ross Moriarty', 'back row', 28, 1.88, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Taine Basham', 'back row', 22, 1.83, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gonzalo Bertranou', 'scrum-half', 28, 1.74, 77, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lewis Jones', 'scrum-half', 29, 1.75, 81, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rhodri Williams', 'scrum-half', 29, 1.79, 81, 22.23);
insert into players (player, position, age, height, weight, year) values ('Angus O''brien', 'fly-half', 28, 1.80, 89, 22.23);
insert into players (player, position, age, height, weight, year) values ('JJ Hanrahan', 'fly-half', 30, 1.83, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sam Davies', 'fly-half', 29, 1.80, 87, 22.23);
insert into players (player, position, age, height, weight, year) values ('Will Reed', 'fly-half', 20, 1.76, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('Aneurin Owen', 'center', 21, 1.80, 89, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cory Allen', 'center', 29, 1.93, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack Dixon', 'center', 27, 1.88, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Max Clark', 'center', 27, 1.90, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sio Tomkinson', 'center', 26, 1.83, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Steff Hughes', 'center', 28, 1.80, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ashton Hewitt', 'winger', 27, 1.80, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jared Rosser', 'winger', 24, 1.83, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rio Dyer', 'winger', 22, 1.86, 94, 22.23);
insert into players (player, position, age, height, weight, year) values ('David Richards', 'fullback', 23, 1.82, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ioan Davies', 'fullback', 22, 1.83, 84, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jordan Williams', 'fullback', 29, 1.73, 81, 22.23);
insert into players (player, position, age, height, weight, year) values ('Angus Williams', 'prop', 28, 1.80, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Boan Venter', 'prop', 25, 1.87, 124, 22.23);
insert into players (player, position, age, height, weight, year) values ('Harrison Courtney', 'prop', 25, 1.84, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lee Roy atalifo', 'prop', 34, 1.80, 134, 22.23);
insert into players (player, position, age, height, weight, year) values ('Luan De bruin', 'prop', 29, 1.83, 128, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nick Auterac', 'prop', 29, 1.83, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Pierre Schoeman', 'prop', 28, 1.84, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Wp Nel', 'prop', 36, 1.82, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Adam Mcburney', 'hooker', 26, 1.83, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dave Cherry', 'hooker', 31, 1.83, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Stuart Mcinally', 'hooker', 32, 1.90, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Glen Young', 'lock', 27, 2.01, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Grant Gilchrist', 'lock', 32, 2.02, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jamie Hodgson', 'lock', 24, 1.97, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marshall Sykes', 'lock', 22, 2.00, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mesulame Kunavula', 'lock', 26, 1.96, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Pierce Phillips', 'lock', 30, 2.03, 119, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ben Muncaster', 'back row', 20, 1.90, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Connor Boyle', 'back row', 22, 1.83, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Hamish Watson', 'back row', 30, 1.85, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jamie Ritchie', 'back row', 26, 1.93, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Luke Crosbie', 'back row', 25, 1.98, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nick Haining', 'back row', 32, 1.93, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sam Skinner', 'back row', 27, 1.96, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Viliame Mata', 'back row', 30, 1.96, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ben Vellacott', 'scrum-half', 27, 1.67, 78, 22.23);
insert into players (player, position, age, height, weight, year) values ('Charlie Shiel', 'scrum-half', 24, 1.78, 83, 22.23);
insert into players (player, position, age, height, weight, year) values ('Henry Pyrgos', 'scrum-half', 33, 1.78, 83, 22.23);
insert into players (player, position, age, height, weight, year) values ('Charlie Savala', 'fly-half', 22, 1.93, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jaco Van der walt', 'fly-half', 28, 1.82, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('James Lang', 'fly-half', 27, 1.83, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cameron Hutchison', 'center', 24, 1.83, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Chris Dean', 'center', 28, 1.88, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mark Bennett', 'center', 29, 1.83, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Matt Currie', 'center', 21, 1.91, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Wes Goosen', 'center', 26, 1.80, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Damien Hoyland', 'winger', 28, 1.78, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Darcy Graham', 'winger', 25, 1.76, 84, 22.23);
insert into players (player, position, age, height, weight, year) values ('Emiliano Boffelli', 'winger', 27, 1.91, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Freddie Owsley', 'winger', 25, 1.93, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack Blain', 'winger', 22, 1.91, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Blair Kinghorn', 'fullback', 25, 1.94, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Henry Immelman', 'fullback', 27, 1.89, 98, 22.23);
insert into players (player, position, age, height, weight, year) values ('Allan Dell', 'prop', 30, 1.85, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Enrique Pieretto heiland', 'prop', 27, 1.87, 122, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jamie Bhatti', 'prop', 29, 1.85, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lucio Sordoni', 'prop', 24, 1.90, 123, 22.23); 
insert into players (player, position, age, height, weight, year) values ('Murphy Walker', 'prop', 22, 1.85, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nathan Mcbeth', 'prop', 24, 1.89, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Oli Kebble', 'prop', 30, 1.91, 124, 22.23);
insert into players (player, position, age, height, weight, year) values ('Simon Berghan', 'prop', 31, 1.93, 126, 22.23);
insert into players (player, position, age, height, weight, year) values ('Zander Fagerson', 'prop', 26, 1.88, 126, 22.23);
insert into players (player, position, age, height, weight, year) values ('Angus Fraser', 'hooker', 22, 1.81, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Fraser Brown', 'hooker', 33, 1.82, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('George Turner', 'hooker', 30, 1.81, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gregor Hiddleston', 'hooker', 20, 1.87, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Johnny Matthews', 'hooker', 29, 1.83, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alex Samuel', 'lock', 19, 2.07, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gregor Brown', 'lock', 21, 1.96, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('JP Du preez', 'lock', 27, 2.08, 130, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lewis Bean', 'lock', 30, 2.03, 129, 22.23);
insert into players (player, position, age, height, weight, year) values ('Max Williamson', 'lock', 20, 2.01, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Richie Gray', 'lock', 33, 2.06, 126, 22.23);
insert into players (player, position, age, height, weight, year) values ('Scott Cummings', 'lock', 25, 1.98, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sintu Manjezi', 'lock', 27, 1.98, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ally Miller', 'back row', 26, 1.93, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack Dempsey', 'back row', 28, 1.91, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Matt Fagerson', 'back row', 24, 1.87, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rory Darge', 'back row', 22, 1.86, 98, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ryan Wilson', 'back row', 33, 1.93, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sione Vailanu', 'back row', 27, 1.85, 127, 22.23);
insert into players (player, position, age, height, weight, year) values ('Thomas Gordon', 'back row', 25, 1.81, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ali Price', 'scrum-half', 29, 1.78, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cam Jones', 'scrum-half', 21, 1.79, 82, 22.23);
insert into players (player, position, age, height, weight, year) values ('George Horne', 'scrum-half', 27, 1.75, 79, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jamie Dobie', 'scrum-half', 21, 1.75, 81, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jordan Lenac', 'scrum-half', 25, 1.77, 85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sean Kennedy', 'scrum-half', 31, 1.73, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('Domingo Miotti', 'fly-half', 26, 1.88, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Duncan Weir', 'fly-half', 31, 1.76, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joel Hodgson', 'fly-half', 30, 1.76, 84, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ross Thompson', 'fly-half', 23, 1.83, 86, 22.23);
insert into players (player, position, age, height, weight, year) values ('Will Hunt', 'fly-half', 24, 1.88, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Huw Jones', 'center', 28, 1.86, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kyle Steyn', 'center', 28, 1.87, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sam Johnson', 'center', 29, 1.85, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sione Tuipulotu', 'center', 25, 1.79, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Stafford Mcdowall', 'center', 24, 1.93, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tom Jordan', 'center', 24, 1.89, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sebastian Cancelliere', 'winger', 29, 1.85, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Walter Fifita', 'winger', 25, 1.95, 1.85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cole Forbes', 'fullback', 23, 1.80,	91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Josh Mckay', 'fullback', 25, 1.83, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ollie Smith', 'fullback', 22, 1.88, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rufus Mclean', 'fullback', 22, 1.81, 84, 22.23);
insert into players (player, position, age, height, weight, year) values ('Andrew Porter', 'prop', 26, 1.84, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cian Healy', 'prop', 35, 1.85, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ed Byrne', 'prop', 29, 1.80, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Michael Alaalatoa', 'prop', 31, 1.91, 130, 22.23);
insert into players (player, position, age, height, weight, year) values ('Michael Milne', 'prop', 22, 1.83, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tadhg Furlong', 'prop', 29, 1.83, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tom Clarkson', 'prop', 22, 1.85, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Vakh Abdaladze', 'prop', 26, 1.88, 121, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dan Sheehan', 'hooker', 24, 1.91, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('James Tracy', 'hooker', 31, 1.84, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ronan Kelleher', 'hooker', 24, 1.85, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Brian Deeny', 'lock', 22, 2.01, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Charlie Ryan', 'lock', 23, 2.03, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('James Ryan', 'lock', 26, 2.03, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jason Jenkins', 'lock', 26, 2.03, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joe Mccarthy', 'lock', 21, 1.98, 119, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ross Molony', 'lock', 28, 1.98, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ryan Baird', 'lock', 23, 1.98, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Caelan Doris', 'back row', 24, 1.93, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack Conan', 'back row', 30, 1.93, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Josh Van der flier', 'back row', 29, 1.83, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Martin Moloney', 'back row', 21, 1.85, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Max Deegan', 'back row', 26, 1.93, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rhys Ruddock', 'back row', 31, 1.91, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Scott Penny', 'back row', 23, 1.85, 104, 22.23);
insert into players (player, position, age, height, weight, year) values ('Will Connors', 'back row', 26, 1.96, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cormac Foley', 'scrum-half', 22, 1.80, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jamison Gibson-park', 'scrum-half', 30, 1.76, 83, 22.23);
insert into players (player, position, age, height, weight, year) values ('Luke Mcgrath', 'scrum-half', 29, 1.75, 84, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nick Mccarthy', 'scrum-half', 27, 1.80,	84, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ciaran Frawley', 'fly-half', 24, 1.91, 98, 22.23);
insert into players (player, position, age, height, weight, year) values ('Harry Byrne', 'fly-half', 23, 1.91, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Johnny Sexton', 'fly-half', 37, 1.88, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ross Byrne', 'fly-half', 27, 1.93, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Charlie Ngatai', 'center', 32, 1.88, 104, 22.23);
insert into players (player, position, age, height, weight, year) values ('Garry Ringrose', 'center', 27, 1.91, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jimmy O''brien', 'center', 25, 1.83, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Robbie Henshaw', 'center', 29, 1.91, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tommy O''brien', 'center', 24, 1.83, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dave Kearney', 'winger', 33, 1.80, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('James Lowe', 'winger', 30, 1.88, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jordan Larmour', 'winger', 25, 1.78, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Liam Turner', 'winger', 23, 1.83, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Hugo Keenan', 'fullback', 26, 1.85, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jamie Osborne', 'fullback', 20, 1.93, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dave Kilcoyne', 'prop', 33, 1.85, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('James French', 'prop', 23, 1.85, 121, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jeremy Loughman', 'prop', 27, 1.85, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Josh Wycherley', 'prop', 23, 1.83, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Keynan Knox', 'prop', 23, 1.85, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Liam O''connor', 'prop', 27, 1.80, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Roman Salanoa', 'prop', 24, 1.83, 123, 22.23);
insert into players (player, position, age, height, weight, year) values ('Stephen Archer', 'prop', 34, 1.88, 121, 22.23);
insert into players (player, position, age, height, weight, year) values ('Chris Moore', 'hooker', 22, 1.85, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Diarmuid Barron', 'hooker', 24, 1.84, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Niall Scannell', 'hooker', 30, 1.85, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Scott Buckley', 'hooker', 22, 1.80, 104, 22.23);
insert into players (player, position, age, height, weight, year) values ('Eoin O''connor', 'lock', 22, 2.01, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Fineen Wycherley', 'lock', 24, 1.96, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jean Kleyn', 'lock', 29, 2.03, 121, 22.23);
insert into players (player, position, age, height, weight, year) values ('Paddy Kelly', 'lock', 22, 2.01, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('RG Snyman', 'lock', 27, 2.06, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tadhg Beirne', 'lock', 30, 1.98, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Thomas Ahern', 'lock', 22, 2.06, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alex Kendellen', 'back row', 21, 1.88, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gavin Coombes', 'back row', 24, 1.98, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack Daly', 'back row', 24, 1.83, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack O''donoghue', 'back row', 28, 1.91, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack O''sullivan', 'back row', 24, 1.89, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('John Hodnett', 'back row', 23, 1.85, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Peter O''mahony', 'back row', 33, 1.91, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Conor Murray', 'scrum-half', 33, 1.88, 94, 22.23);
insert into players (player, position, age, height, weight, year) values ('Craig Casey', 'scrum-half', 23, 1.65, 76, 22.23);
insert into players (player, position, age, height, weight, year) values ('Neil Cronin', 'scrum-half', 29, 1.73, 83, 22.23);
insert into players (player, position, age, height, weight, year) values ('Paddy Patterson', 'scrum-half', 23, 1.75, 75, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ben Healy', 'fly-half', 23, 1.91, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack Crowley', 'fly-half', 22, 1.83, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joey Carbery', 'fly-half', 26, 1.83, 86, 22.23);
insert into players (player, position, age, height, weight, year) values ('Antoine Frisch', 'center', 26, 1.88, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Chris Farrell', 'center', 29, 1.91, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dan Goggin', 'center', 27, 1.88, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Malakai Fekitoa', 'center', 30, 1.87, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rory Scannell', 'center', 28, 1.79, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Shane Daly', 'center', 25, 1.91, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Andrew Conway', 'winger', 31, 1.80, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Calvin Nash', 'winger', 25, 1.80, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Keith Earls', 'winger', 35, 1.80, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Liam Coombes', 'winger', 25, 1.91, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Simon Zebo', 'winger', 32, 1.88, 94, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mike Haley', 'fullback', 28, 1.91, 94, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ben Warren', 'prop', 22, 1.85, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gareth Thomas', 'prop', 29, 1.88, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Garyn Phillips', 'prop', 21, 1.83, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nicky Smith', 'prop', 28, 1.83, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rhys Henry', 'prop', 24, 1.73, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tom Botha', 'prop', 32, 1.79, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tomas Francis', 'prop', 30, 1.86, 135, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dewi Lake', 'hooker', 23, 1.85, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Elvis Taione', 'hooker', 39, 1.80, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sam Parry', 'hooker', 30, 1.86, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Scott Baldwin', 'hooker', 34, 1.90, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Adam Beard', 'lock', 26, 2.03, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alun Wyn jones', 'lock', 37, 1.98, 119, 22.23);
insert into players (player, position, age, height, weight, year) values ('Bradley Davies', 'lock', 35, 1.98, 122, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack Regan', 'lock', 25, 1.99, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rhys Davies', 'lock', 23, 1.97, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Will Griffiths', 'lock', 23, 1.93, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dan Lydiate', 'back row', 34, 1.94, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ethan Roots', 'back row', 24, 1.88, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jac Morgan', 'back row', 22, 1.80, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Justin Tipuric', 'back row', 33, 1.88, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Morgan Morris', 'back row', 24, 1.83, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sam Cross', 'back row', 30, 1.90, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sam Moore', 'back row', 24, 1.98, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Will Hickey', 'back row', 20, 1.91, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Harri Morgan', 'scrum-half', 22, 1.77, 84, 22.23);
insert into players (player, position, age, height, weight, year) values ('Matthew Aubrey', 'scrum-half', 25, 1.68, 85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Reuben Morgan-williams', 'scrum-half', 24, 1.80,	85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rhys Webb', 'scrum-half', 33, 1.83, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cai Evans', 'fly-half', 23, 1.85, 84, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gareth Anscombe', 'fly-half', 31, 1.83, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jack Walsh', 'fly-half', 23, 1.84, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Stephen Myler', 'fly-half', 38, 1.80, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joe Hawkins', 'center', 20, 1.83, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kieran Williams', 'center', 25, 1.78, 79, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mike Collins', 'center', 29, 1.86, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Osian Knott', 'center', 22, 1.88, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Owen Watkin', 'center', 25, 1.88, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tiaan Thomas-wheeler', 'center', 22, 1.91, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alex Cuthbert', 'winger', 32, 1.98, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('George North', 'winger', 30, 1.94, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Keelan Giles', 'winger', 24, 1.73, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('Luke Morgan', 'winger', 30, 1.75, 81, 22.23);
insert into players (player, position, age, height, weight, year) values ('Daniel Evans', 'fullback', 33, 1.83, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mat Protheroe', 'fullback', 26, 1.81, 81, 22.23);
insert into players (player, position, age, height, weight, year) values ('Max Nagy', 'fullback', 26, 1.93, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alex Jeffries', 'prop', 27, 1.93, 127, 22.23);
insert into players (player, position, age, height, weight, year) values ('Javan Sebastian', 'prop', 28, 1.77, 123, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kemsley Mathias', 'prop', 23, 1.85, 121, 22.23);
insert into players (player, position, age, height, weight, year) values ('Phil Price', 'prop', 33, 1.85, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Samson Lee', 'prop', 29, 1.80, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Steff Thomas', 'prop', 25, 1.83, 122, 22.23);
insert into players (player, position, age, height, weight, year) values ('Willgriff John', 'prop', 29, 1.91, 127, 22.23);
insert into players (player, position, age, height, weight, year) values ('Wyn Jones', 'prop', 30, 1.84, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dafydd Hughes', 'hooker', 26, 1.79, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ken Owens', 'hooker', 35, 1.85, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ryan Elias', 'hooker', 27, 1.87, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Shaun Evans', 'hooker', 26, 1.83, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Taylor Davies', 'hooker', 27, 1.84, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Griff Evans', 'lock', 21, 1.98, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jac Price', 'lock', 22, 1.98, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Josh Helps', 'lock', 27, 1.97, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lewis Rawlins', 'lock', 32, 1.99, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Morgan Jones', 'lock', 23, 2.00, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sam Lousi', 'lock', 31, 1.99, 122, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tom Price', 'lock', 29, 2.03, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Aaron Shingler', 'back row', 35, 1.97, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Blade Thomson', 'back row', 31, 1.98, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Carwyn Tuipulotu', 'back row', 21, 1.88, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dan Davis', 'back row', 24, 1.82, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Iestyn Rees', 'back row', 23, 1.89, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Iwan Shenton', 'back row', 22, 1.93, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Josh Macleod', 'back row', 25, 1.89, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sione Kalamafoni', 'back row', 34, 1.96, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tomás Lezana', 'back row', 28, 1.88, 104, 22.23);
insert into players (player, position, age, height, weight, year) values ('Vaea Fifita', 'back row', 30, 1.96, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dane Blacker', 'scrum-half', 24, 1.78, 78, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gareth Davies', 'scrum-half', 32, 1.78, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kieran Hardy', 'scrum-half', 26, 1.84, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dan Jones', 'fly-half', 26, 1.83, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rhys Patchell', 'fly-half', 29, 1.90, 94, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sam Costelow', 'fly-half', 21, 1.75, 83, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ioan Nicholas', 'center', 24, 1.82, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joe Roberts', 'center', 22, 1.82, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Johnny Williams', 'center', 25, 1.91, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jonathan Davies', 'center', 34, 1.86, 104, 22.23);
insert into players (player, position, age, height, weight, year) values ('Scott Williams', 'center', 32, 1.87, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Corey Baldwin', 'winger', 23, 1.83, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Johnny Mcnicholl', 'winger', 32, 1.87, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ryan Conbeer', 'winger', 23, 1.77, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Steff Evans', 'winger', 28, 1.82, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tom Rogers', 'winger', 23, 1.85, 87, 22.23);
insert into players (player, position, age, height, weight, year) values ('Leigh Halfpenny', 'fullback', 33, 1.78, 85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Andy Warwick', 'prop', 31, 1.78, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Callum Reid', 'prop', 23, 1.83, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Eric O''sullivan', 'prop', 26, 1.86, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gareth Milasinovich', 'prop', 26, 1.91, 134, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jeffery Toomaga-allen', 'prop', 31, 1.92, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marty Moore', 'prop', 31, 1.80, 126, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tom O''toole', 'prop', 24, 1.85, 124, 22.23);
insert into players (player, position, age, height, weight, year) values ('Declan Moore', 'hooker', 26, 1.84, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('John Andrew', 'hooker', 29, 1.80,	103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rob Herring', 'hooker', 32, 1.85, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tom Stewart', 'hooker', 21, 1.85, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alan O''connor', 'lock', 30, 1.97, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cormac Izuchukwu', 'lock', 22, 2.01, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Frank Bradshaw', 'lock', 27, 2.05, 119, 22.23);
insert into players (player, position, age, height, weight, year) values ('Iain Henderson', 'lock', 30, 1.98, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kieran Treadwell', 'lock', 26, 1.99, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sam Carter', 'lock', 33, 2.01, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('David Mccann', 'back row', 22, 1.93, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Duane Vermeulen', 'back row', 36, 1.93, 119, 22.23);
insert into players (player, position, age, height, weight, year) values ('Greg Jones', 'back row', 26, 1.96, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jordi Murphy', 'back row', 31, 1.88, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marcus Rea', 'back row', 25, 1.89, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Matty Rea', 'back row', 29, 1.93, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nick Timoney', 'back row', 27, 1.88, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sean Reffell', 'back row', 24, 1.80, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dave Shanahan', 'scrum-half', 29, 1.76, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('John Cooney', 'scrum-half', 32, 1.78, 87, 22.23);
insert into players (player, position, age, height, weight, year) values ('Michael Mcdonald', 'scrum-half', 23, 1.78, 85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nathan Doak', 'scrum-half', 20, 1.85, 87, 22.23);
insert into players (player, position, age, height, weight, year) values ('Angus Curtis', 'fly-half', 24, 1.78, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Billy Burns', 'fly-half', 28, 1.83, 87, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ian Madigan', 'fly-half', 33, 1.81, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mike Lowry', 'fly-half', 24, 1.71, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('Aaron Sexton', 'center', 22, 1.88, 94, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ben Moxham', 'center', 21, 1.91, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jacob Stockdale', 'center', 26, 1.91, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('James Hume', 'center', 24, 1.88, 98, 22.23);
insert into players (player, position, age, height, weight, year) values ('Luke Marshall', 'center', 31, 1.80, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Stewart Moore', 'center', 23, 1.83, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Stuart Mccloskey', 'center', 30, 1.93, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Will Addison', 'center', 30, 1.85, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Craig Gilroy', 'winger', 31, 1.83, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rob Lyttle', 'winger', 25, 1.75, 85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Robert Baloucoune', 'winger', 25, 1.94, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ethan Mcilroy', 'fullback', 22, 1.88, 86, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jake Flannery', 'fullback', 23, 1.83, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alessio Sanavia',	'prop', 26, 1.79, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Daniele Rimpelli', 'prop', 25, 1.88, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ion Neculai', 'prop', 21, 1.89, 135, 22.23);
insert into players (player, position, age, height, weight, year) values ('Juan Pitinari', 'prop', 27, 1.87, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Luca Rizzoli', 'prop', 20, 1.78, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Matteo Nocera', 'prop', 23, 1.94, 128, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mattia Mazzanti', 'prop', 20, 1.81, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Muhamed Hasa', 'prop', 21, 1.83, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Paolo Buonfiglio', 'prop', 27, 1.83, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Riccardo Genovese', 'prop', 20, 1.89, 126, 22.23);
insert into players (player, position, age, height, weight, year) values ('Giampietro Ribaldi', 'hooker', 25, 1.86, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jacques Du toit', 'hooker', 28, 1.83, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Luca Bigi', 'hooker', 31, 1.82, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marco Manfredi', 'hooker', 25, 1.83, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Andrea Zambonin', 'lock', 22, 2.02, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('David Sisi', 'lock', 29, 1.95, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dennis Visser', 'lock', 29, 2.00, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gabriele Venditti', 'lock', 25, 2.00, 135, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jan Uys', 'lock', 28, 1.99, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joshua Furno', 'lock', 32, 2.00, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Leonard Krumov', 'lock', 26, 1.98, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Davide Ruggeri', 'back row', 23, 1.89, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Giacomo Ferrari', 'back row', 20, 1.90, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Giovanni Licata', 'back row', 25, 1.93, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Guido Volpi', 'back row', 27, 1.93, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Iacopo Bianchi', 'back row', 24, 1.88, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Johan Meyer', 'back row', 29, 1.93, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Luca Andreani', 'back row', 21, 1.90, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('MJ Pelser', 'back row', 24, 1.85, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Taina Fox-matamua', 'back row', 25, 1.92, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alessandro Fusco', 'scrum-half', 22, 1.85, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Chris Cook', 'scrum-half', 31, 1.78, 94, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gonzalo Garcia', 'scrum-half', 23, 1.73, 78, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nicolò Casilio', 'scrum-half', 24, 1.80, 85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ratko Jelic', 'scrum-half', 22, 1.72, 74, 22.23);
insert into players (player, position, age, height, weight, year) values ('Antonio Rizzi', 'fly-half', 24, 1.80, 87, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joey Caputo', 'fly-half', 22, 1.82, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nicolò Teneggi', 'fly-half', 19, 1.79, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tiff Eden', 'fly-half', 27, 1.83, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Damiano Mazza', 'center', 23, 1.83, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Enrico Lucchin', 'center', 27, 1.88, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Erich Cronjé', 'center', 25, 1.84, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Franco (jr) smith', 'center', 22, 1.82, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Matteo Moscardi', 'center', 22, 1.83, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tommaso Boni', 'center', 29, 1.87, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kobus Van wyk', 'winger', 30, 1.90, 98, 22.23);
insert into players (player, position, age, height, weight, year) values ('Latu Latunipulu', 'winger', 25, 1.81, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Pierre Bruno', 'winger', 26, 1.78, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Simone Gesi', 'winger', 21, 1.83, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jacopo Trulla', 'fullback', 22, 1.83, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lorenzo Pani', 'fullback', 20, 1.90, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Richard Kriel', 'fullback', 22, 1.94, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dylan Smith', 'prop', 28, 1.81, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('François Klopper', 'prop', 23, 1.89, 124, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gerhard Steenekamp', 'prop', 25, 1.94, 128, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jacques Van rooyen', 'prop', 35, 1.86, 122, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jan-Hendrik Wessels', 'prop', 21, 1.93, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lizo Gqoboka', 'prop', 32, 1.83, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mornay Smith', 'prop', 24, 1.81, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Robert Hunt', 'prop', 26, 1.85, 122, 22.23);
insert into players (player, position, age, height, weight, year) values ('Simphiwe Matanzima', 'prop', 25, 1.82, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Bismarck Du plessis', 'hooker', 38, 1.89, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joe Van zyl', 'hooker', 23, 1.84, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Johan Grobbelaar', 'hooker', 24, 1.82, 98, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sidney Tobias', 'hooker', 33, 1.76, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Elrigh Louw', 'lock', 23, 1.95, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jacques Du plessis', 'lock', 29, 2.01, 125, 22.23);
insert into players (player, position, age, height, weight, year) values ('Janko Swanepoel', 'lock', 23, 2.00, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Reinhardt Ludwig', 'lock', 20, 1.99, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ruan Nortjé', 'lock', 24, 2.00, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ruan Vermaak', 'lock', 24, 1.99, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Walt Steenkamp', 'lock', 27, 2.03, 121, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cyle Brink', 'back row', 28, 1.91, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marcell Coetzee', 'back row', 31, 1.91, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marco Van staden', 'back row', 27, 1.84, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mihlali Mosi', 'back row', 26, 1.90, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Muller Uys', 'back row', 24, 1.91, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Phumzile Maqondwana', 'back row', 25, 1.87, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('WJ Steenkamp', 'back row', 20, 1.90, 104, 22.23);
insert into players (player, position, age, height, weight, year) values ('Embrose Papier', 'scrum-half', 25, 1.71, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('Keagan Johannes', 'scrum-half', 22, 1.77, 75, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marco Jansen van vuren', 'scrum-half', 26, 1.86, 94, 22.23);
insert into players (player, position, age, height, weight, year) values ('Zak Burger', 'scrum-half', 24, 1.74, 83, 22.23);
insert into players (player, position, age, height, weight, year) values ('Chris Smith', 'fly-half', 28, 1.81, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Juan Mostert', 'fly-half', 22, 1.93, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Morné Steyn', 'fly-half', 38, 1.83, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Chris Smit', 'center', 27, 1.82, 86, 22.23);
insert into players (player, position, age, height, weight, year) values ('Harold Vorster', 'center', 29, 1.86, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lionel Mapoe', 'center', 34, 1.83, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Stedman Gans', 'center', 25, 1.80,	85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Wandisile Simelane', 'center', 24, 1.78, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Canan Moodie', 'winger', 19, 1.90,	89, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cornal Hendricks', 'winger', 34, 1.89, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('James Verity-amm', 'winger', 28, 1.85, 86, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kurt-Lee Arendse', 'winger', 26, 1.80,	84, 22.23);
insert into players (player, position, age, height, weight, year) values ('S''Busiso Nkosi', 'winger', 26, 1.81, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Stravino Jacobs', 'winger', 22, 1.80, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('David Kriel', 'fullback', 23, 1.94, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Johan Goosen', 'fullback', 30, 1.84, 89, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ruan Combrinck', 'fullback', 32, 1.83, 99, 22.23);
insert into players (player, position, age, height, weight, year) values ('Carlü Sadie', 'prop', 25, 1.82, 147, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dian Bleuler', 'prop', 23, 1.76, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Hanru Jacobs', 'prop', 22, 1.82, 122, 22.23);
insert into players (player, position, age, height, weight, year) values ('Khutha Mchunu', 'prop', 25, 1.84, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Khwezi Mona', 'prop', 30, 1.81, 116, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lourens Adriaanse', 'prop', 34, 1.81, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ntuthuko Mchunu', 'prop', 23, 1.88, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ox Nché', 'prop', 27, 1.75, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Thomas Du toit', 'prop', 27, 1.88, 136, 22.23);
insert into players (player, position, age, height, weight, year) values ('Bongi Mbonambi', 'hooker', 31, 1.86, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dan Jooste', 'hooker', 24, 1.87, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Fez Mbatha', 'hooker', 23, 1.80, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kerron Van vuuren', 'hooker', 27, 1.88, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Eben Etzebeth', 'lock', 30, 2.03, 122, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gerbrandt Grobler', 'lock', 30, 2.00,	120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Hyron Andrews', 'lock', 27, 2.01, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Justin Basson', 'lock', 28, 1.95, 121, 22.23);
insert into players (player, position, age, height, weight, year) values ('Le Roux roets', 'lock', 27, 2.01, 138, 22.23);
insert into players (player, position, age, height, weight, year) values ('Reniel Hugo', 'lock', 32, 1.97, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dylan Richardson', 'back row', 23, 1.84, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Henco Venter', 'back row', 30, 1.87, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('James Venter', 'back row', 26, 1.82, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jeandré Labuschagne', 'back row', 23, 1.92, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mpilo Gumede', 'back row', 22, 1.92, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Phepsi Buthelezi', 'back row', 23, 1.88, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sikhumbuzo Notshe', 'back row', 29, 1.86, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Siya Kolisi', 'back row', 31, 1.86, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Thembelani Bholi', 'back row', 32, 1, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tino Mavesere', 'back row', 23, 1.89, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Vincent Tshituka', 'back row', 24, 1.95, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cameron Wright', 'scrum-half', 28, 1.81, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Grant Williams', 'scrum-half', 26, 1.74, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jaden Hendrikse', 'scrum-half', 22, 1.84, 87, 22.23); 
insert into players (player, position, age, height, weight, year) values ('Zee Mkhabela', 'scrum-half', 27, 1.67, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('Boeta Chamberlain', 'fly-half', 23, 1.80,	83, 22.23);
insert into players (player, position, age, height, weight, year) values ('Curwin Bosch', 'fly-half', 25, 1.80, 85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Fred Zeilinga', 'fly-half', 29, 1.75, 82, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lionel Cronjé', 'fly-half', 33, 1.84, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ben Tapuai', 'center', 33, 1.80, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lukhanyo Am', 'center', 28, 1.86, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Murray Koster', 'center', 23, 1.88, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rohan Janse van rensburg', 'center', 28, 1.85, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Anthonie Volmink', 'winger', 32, 1.80, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Eduan Keyter', 'winger', 26, 1.84, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Makazole Mapimpi', 'winger', 32, 1.87, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marnus Potgieter', 'winger', 23, 1.87, 98, 22.23);
insert into players (player, position, age, height, weight, year) values ('Werner Kok', 'winger', 29, 1.79, 94, 22.23);
insert into players (player, position, age, height, weight, year) values ('Yaw Penxe', 'winger', 25, 1.81, 82, 22.23);
insert into players (player, position, age, height, weight, year) values ('Aphelele Fassi', 'fullback', 24, 1.89, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Muller Du plessis', 'fullback', 23, 1.87, 85, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nevaldo Fleurs', 'fullback', 22, 1.82, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Thaakir Abrahams', 'fullback', 22, 1.75, 76, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ali Vermaak', 'prop', 36, 1.78, 110, 22.23); 
insert into players (player, position, age, height, weight, year) values ('Brok Harris', 'prop', 37, 1.86, 121, 22.23); 
insert into players (player, position, age, height, weight, year) values ('Frans Malherbe', 'prop', 31, 1.90, 138, 22.23); 
insert into players (player, position, age, height, weight, year) values ('Kwenzo Blose', 'prop', 25, 1.87, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Lee-Marvin Mazibuko', 'prop', 25, 1.80,	110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Leon Lyons', 'prop', 23, 1.88, 118, 22.23);
insert into players (player, position, age, height, weight, year) values ('Neethling Fouché', 'prop', 29, 1.87, 119, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sazi Sandi', 'prop', 24, 1.81, 122, 22.23);
insert into players (player, position, age, height, weight, year) values ('Steven Kitshoff', 'prop', 30, 1.83, 123, 22.23);
insert into players (player, position, age, height, weight, year) values ('André-Hugo Venter', 'hooker', 21, 1.87, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Chad Solomon', 'hooker', 28, 1.79, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('JJ Kotzé', 'hooker', 21, 1.87, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Joseph Dweba', 'hooker', 26, 1.80, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Siyabonga Ntubeni', 'hooker', 31, 1.73, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Adré Smith', 'lock', 25, 2.04, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ben-Jason Dixon', 'lock', 24, 1.98, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Connor Evans', 'lock', 20, 1.98, 113, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ernst Van rhyn', 'lock', 25, 1.92, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gary Porter', 'lock', 26, 2.01, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marvin Orie', 'lock', 29, 1.98, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Salmaan Moerat', 'lock', 24, 2.00, 122, 22.23);
insert into players (player, position, age, height, weight, year) values ('Deon Fourie', 'back row', 36, 1.78, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Evan Roos', 'back row', 22, 1.92, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Hacjivah Dayimani', 'back row', 25, 1.88, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Junior Sipato pokomela', 'back row', 25, 1.90, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Keke Morabe', 'back row', 21, 1.88, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marcel Theunissen', 'back row', 23, 1.92, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Nama Xaba', 'back row', 25, 1.85, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Paul De villiers', 'back row', 19, 1.80, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Willie Engelbrecht', 'back row', 30, 1.91, 109, 22.23);
insert into players (player, position, age, height, weight, year) values ('Godlen Masimla', 'scrum-half', 30, 1.77, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('Herschel Jantjies', 'scrum-half', 26, 1.67, 75, 22.23);
insert into players (player, position, age, height, weight, year) values ('Imad Khan', 'scrum-half', 18, 1.78, 77, 22.23);
insert into players (player, position, age, height, weight, year) values ('Paul De wet', 'scrum-half', 26, 1.76, 83, 22.23);
insert into players (player, position, age, height, weight, year) values ('Stefan Ungerer', 'scrum-half', 28, 1.83, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Damian Willemse', 'fly-half', 24, 1.87, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Kade Wolhuter', 'fly-half', 21, 1.82, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Manie Libbok', 'fly-half', 25, 1.79, 80, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sacha Mngomezulu', 'fly-half', 20, 1.85, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Alapati Leiua', 'center', 34, 1.85, 100, 22.23);
insert into players (player, position, age, height, weight, year) values ('Chris Hollis', 'center', 24, 1.91, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Cornel Smit', 'center', 25, 1.83, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Dan Du plessis', 'center', 28, 1.93, 103, 22.23);
insert into players (player, position, age, height, weight, year) values ('Juan De jongh', 'center', 34, 1.77, 89, 22.23);
insert into players (player, position, age, height, weight, year) values ('Mnombo Zwelendaba', 'center', 22, 1.88, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ruhan Nel', 'center', 31, 1.91, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Suleiman Hartzenberg', 'center', 19, 1.82, 91, 22.23);
insert into players (player, position, age, height, weight, year) values ('Angelo Davids', 'winger', 23, 1.78, 84, 22.23);
insert into players (player, position, age, height, weight, year) values ('Leolin Zas', 'winger', 26, 1.84, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Seabelo Senatla', 'winger', 29, 1.79, 89, 22.23);
insert into players (player, position, age, height, weight, year) values ('Clayton Blommetjies', 'fullback', 32, 1.83, 89, 22.23);
insert into players (player, position, age, height, weight, year) values ('Tristan Leyds', 'fullback', 25, 1.83, 74, 22.23);
insert into players (player, position, age, height, weight, year) values ('Asenathi Ntlabakanye', 'prop', 23, 1.82, 153, 22.23); 
insert into players (player, position, age, height, weight, year) values ('Jean-Pierre Smith', 'prop', 32, 1.86, 124, 22.23);
insert into players (player, position, age, height, weight, year) values ('Morgan Naudé', 'prop', 24, 1.81, 108, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ruan Dreyer', 'prop', 32, 1.86, 115, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ruan Smith', 'prop', 32, 1.86, 123, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sti Sithole', 'prop', 29, 1.80, 114, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jaco Visagie', 'hooker', 30, 1.88, 107, 22.23);
insert into players (player, position, age, height, weight, year) values ('Morné Brandon', 'hooker', 21, 1.84, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('PJ Botha', 'hooker', 24, 1.81, 105, 22.23);
insert into players (player, position, age, height, weight, year) values ('Darrien-Lane Landsberg', 'lock', 24, 1.96, 111, 22.23);
insert into players (player, position, age, height, weight, year) values ('Pieter Jansen van vuren', 'lock', 31, 1.94, 110, 22.23);
insert into players (player, position, age, height, weight, year) values ('Reinhard Nothnagel', 'lock', 25, 2.02, 117, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ruan Venter', 'lock', 19, 1.85, 120, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ruben Schoeman', 'lock', 26, 1.99, 124, 22.23);
insert into players (player, position, age, height, weight, year) values ('Emmanuel Tshituka', 'back row', 22, 1.94, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Francke Horn', 'back row', 23, 1.90, 106, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jaco Kriel', 'back row', 33, 1.84, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ruhan Straeuli', 'back row', 23, 1.93, 112, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sibusiso Sangweni', 'back row', 21, 1.89, 102, 22.23);
insert into players (player, position, age, height, weight, year) values ('Travis Gordon', 'back row', 23, 1.88, 104, 22.23);
insert into players (player, position, age, height, weight, year) values ('André Riaan warner', 'scrum-half', 29, 1.84, 93, 22.23);
insert into players (player, position, age, height, weight, year) values ('Morné Van den berg', 'scrum-half', 24, 1.75, 82, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sanele Nohamba', 'scrum-half', 23, 1.67, 69, 22.23);
insert into players (player, position, age, height, weight, year) values ('James Tedder', 'fly-half', 25, 1.91, 95, 22.23);
insert into players (player, position, age, height, weight, year) values ('Jordan Hendrikse', 'fly-half', 21, 1.86, 89, 22.23);
insert into players (player, position, age, height, weight, year) values ('Zander Du plessis', 'fly-half', 22, 1.90, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Henco Van wyk', 'center', 21, 1.80, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Manuel Rass', 'center', 24, 1.74, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Marius Louw', 'center', 26, 1.82, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Matt More', 'center', 23, 1.92, 101, 22.23);
insert into players (player, position, age, height, weight, year) values ('Quan Horn', 'center', 21, 1.80, 84, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rynhardt Jonker', 'center', 22, 1.80, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Sango Xamlashe', 'center', 23, 1.81, 96, 22.23);
insert into players (player, position, age, height, weight, year) values ('Edwill Van der merwe', 'winger', 26, 1.81, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Ilunga Mukendi', 'winger', 25, 1.84, 88, 22.23);
insert into players (player, position, age, height, weight, year) values ('Rabz Maxwane', 'winger', 27, 1.81, 90, 22.23);
insert into players (player, position, age, height, weight, year) values ('Stean Pienaar', 'winger', 25, 1.78, 97, 22.23);
insert into players (player, position, age, height, weight, year) values ('Andries Coetzee', 'fullback', 32, 1.81, 92, 22.23);
insert into players (player, position, age, height, weight, year) values ('Gianni Lombard', 'fullback', 24, 1.78, 78, 22.23);

alter table players
add column team char(20);

update players
set team = 
(select team
from teams
where players.id = teams.id); -- inserted team in players from teams table
